lib/jovo.js
When attribute value is equal to zero, it triggers an error as if the attribute didn't exist
=> :bug: Fixed getSessionAttribute(name) issue

lib/jovo.js
If I've got a `WelcomeIntent` in the default handler and then I set the skill context to a `FIRST_STATE` state, and invoke the `WelcomeIntent` in this other state, I get the following error:
```
TypeError: Cannot read property 'toString' of undefined
at getParamNames (/Users/octaviomenocal/mytest/src/node_modules/jovo-framework/lib/jovo.js:964:21)
at Jovo.getSortedArgumentsInput (/Users/octaviomenocal/mytest/src/node_modules/jovo-framework/lib/jovo.js:359:26)
at Jovo.handleStateIntentRequest (/Users/octaviomenocal/mytest/src/node_modules/jovo-framework/lib/jovo.js:298:25)
at Jovo.handleIntentRequest (/Users/octaviomenocal/mytest/src/node_modules/jovo-framework/lib/jovo.js:254:18)
at Jovo.execute (/Users/octaviomenocal/mytest/src/node_modules/jovo-framework/lib/jovo.js:190:18)
at …
```
=> :bug: Fixed unknown intent in state issue

lib/jovo.js, test/tests.js
- When redirecting from one intent to another state and intent, the state was not added to the session attributes, so it would always remain in the same state.
- If one attribute is not in the session object, the developers should know better what to do with an `undefined` value instead of throwing an error
=> :bug: Fixed issues when redirecting intents

lib/platforms/alexa/alexaSkill.js
When using this method:
```
app.toStateIntent('anotherState', 'anotherIntent');
```
The new state is saved in the `response (AlexaResponse)` object, however, when calling the `app.getState()` method, it first looks for the old state in the request when I already changed it in the response to the new one.
=> 🐛 Fixed getState priority

index.js
Relates to https://github.com/jovotech/jovo-cli/pull/2
Right now the webhook start allows for use with options by using commander. But it does so by verifying the number of arguments. 
Added an exception so that it can be called by the external proxy command if that PR is accepted.
=> Allows jovo-webhook to be called by external proxy command.

lib/integrations/analytics/bespokenAnalytics.js
These lines were returning the following error:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: jovoSourceObject.getRequest(...).getRequestObject is not a function`
Removing the `.getRequestObject()` solves the issue, and was able to send data effectively to Bespoken.
=> Fix bespoken source object calls

examples/README.md
`./examples/indexRenderTemplate.js` will add `examples` twice so removing `examples` will fix the links :)
=> Fix examples link in examples readme

examples/google_action_specific/indexGoogleAssistantCards.js, lib/platforms/googleaction/googleActionResponse.js
This option for the Basic Card is currently missing from the API. 
See: https://developers.google.com/actions/assistant/responses#basic_card
=> Added Image Display Option feature for Google Action Basic Card

lib/platforms/googleaction/googleAction.js, lib/platforms/googleaction/googleActionResponse.js
When I want to drop several attributes using `app.setSessionAttributes(myAttributes);` in my `NEW_SESSION` or `LAUNCH` functions, I'm simply not able to, since the `session` context is not initialized.
=> 🐛 Fixed setSessionAttributes issue on Google Actions

docs/03_app-configuration/02_server/webhook.md
With `const {WebhookVerified} = require('jovo-framework');` you get an error since the code below still uses `Webhook`
=> :memo: WebhookVerified fix

lib/platforms/speechBuilder.js
I've added three methods to the `speechBuilder` class:
- `addCardinal`
- `addOrdinal`
- `addCharacters`
These methods do nothing but to call the existing methods `addSayAsCardinal`, `addSayAsOrdinal` and `addSayAsCharacters`, respectively, and to pass their arguments (`number` or `characters`, `condition` and `probability`). In this sense, they provide an alias for the three existing functions.
This pull request is motivated by the fact that I use those functions occasionally, but couldn't remember their names and had to look them up every time I used them.
=> Added aliases for Speechbuilder's 'say-as' methods

lib/platforms/googleaction/googleAction.js, lib/platforms/googleaction/request/dialogFlowV2Request.js, package.json
This PR fixes #116 where inputs are passed as plain strings rather than objects. It also handles the case where `res.contextOut` is `undefined` which happens when V2 requests are issued by the dialogflow web interface.
**Notes:**
In V1 the input objects also have a `key` and `id` property that both contain the value. I have no idea what they are for.
I had to add `dashbot` as devDependency in order to get all tests passing.
I tried to add a test, but failed to find a good starting point.
=> Fix dialogflow V2 input handling (issue #116)

lib/platforms/googleaction/request/dialogFlowV2Request.js, lib/platforms/googleaction/request/googleActionDialogFlowRequest.js, lib/platforms/googleaction/request/googleActionDialogFlowV2Request.js
`this.getTimestamp()` causes infinite loop
=>  🐛 fixes getTimestamp() on googleAction requests v1 & v2

lib/platforms/googleaction/googleActionSpeechBuilder.js, lib/platforms/speechBuilder.js, package-lock.json, package.json, test/platforms/testJovoSpeechBuilder.js
This PR adds support for `<phoneme>` tags to the SpeechBuilder class.
Since Google does not support phonemes the GoogleActionSpeechBuilder adds the text _as-is_.
=> Add <phoneme> support to SpeechBuilder

docs/07_advanced/README.md, lib/app.js, test/integrations/plugin.js
This PR removes the need to specify a name when registering plugins and uses the class name as default. The old way is still supported, though. I have updated the docs to only show the new way since it is simpler and less confusing ("why should I specify a name?").
=> Register plugins without a name

lib/integrations/db/dynamoDb.js, lib/jovo.js
DynamoDB does not support empty Strings. If the session contains empty (or `null`) values one gets the following error upon save:
> ValidationException: One or more parameter values were invalid: An AttributeValue may not contain an empty string
The error is not properly handled and yields an unhandled promise rejection error.
This PR addresses both issues and emits a new app-event called `responseError` to allow plugins to report/log the error.
=> Prevent (and gracefully handle) DynamoDB errors

docs/03_app-configuration/02_server/README.md
Update hyperlink for the AWS Lambda link on the /docs/server page to link to /docs/server/aws-lambda, not /docs/server/webhook
=> Update hyperlink to AWS Lambda docs

docs/04_app-logic/03_output/README.md
Fixed a typo in the JS example for the repeat() function on the /docs/output page.
=> Fix typo in JS example for repeat() function

docs/05_platform-specifics/amazon-alexa/audioplayer.md, lib/platforms/alexaSkill/audioPlayer.js
This PR adds support for setting the Title, Subtitle, Artwork, and Background image for an audio track for Alexa's audio player.
=> Adding support for audio track metadata in the Alexa Audio Player.

docs/01_getting-started/README.md
The link for "Voice App Basics" on the Installation page [under step 3](https://www.jovo.tech/docs/installation#3-create-a-language-model) went to a 404 when I clicked on it. I made it not do that by adding a missing `./`. I look forward to using Jovo in upcoming projects!
=> Fixed broken link on installation page.

docs/05_platform-specifics/amazon-alexa/skillevents.md
Added to existing docs to show for each event what data (userId, permissions) is available and how to access it. Showed how to delete a user when a skill is disabled. Added section on Staging to show how different stages can set the endpoint to handle skill events.
=> Update Skill Events docs including new Staging section

lib/platforms/alexaSkill/inSkillPurchase.js
According to the docs, for now it is allowed to do ISP only in the US market:
https://developer.amazon.com/docs/in-skill-purchase/isp-faqs.html
When trying to sell products for non-US locales Alexa sends an error but you still get a response from Alexa. In my case, I was working with an Australian guy who has an `en-US` skill. When he tried to test it out, his AMZ account was associated with the Australian market, and even though he switched to work with the `en-US` locale in the simulator, the Alexa service still recognized the Australian origin and sent the far east endpoint.
=> 🔨 Added validation method for ISP and en-US locale

lib/platforms/alexaSkill/gadgetController.js
Currently, if I add a `SequenceBuilder` to an `AnimationBuilder` it will first `build()` will be called and the result will be added to the `AnimationBuilder`, then the original `SequenceBuilder` object is added.
=> Fix SequenceBuilder being added multiple times

lib/platforms/alexaSkill/alexaSkill.js
When an error is returned from Alexa, an exception is thrown because the `getSessionAttributes` method isn't a member of `ErrorRequest`. This PR adds a check for the existence of `getSessionAttributes`.
=> Fix: handle requests without session attributes

docs/README.md
The missing `https://` rendered a link to https://github.com/jovotech/jovo-framework-nodejs/blob/v2/docs/www.jovo.tech/newsletter
=> Fix broken link to newsletter sign-up form

lib/platforms/alexaSkill/alexaUser.js
Fixes issue with reminders API token. It seems for the new reminders endpoint the apiAccessToken should be used as the Bearer rather than the consentToken.
=> Reminders Fix

jovo-integrations/jovo-platform-alexa/src/modules/Cards.ts
`SimpleCard` didn't include the `content` property, because it tried to access `text`, which doesn't exist.
=>  🐛 SimpleCard didn't include content

jovo-integrations/jovo-platform-alexa/src/modules/AlexaCore.ts
Since the migration to 2.x, JSON send to alexa isn't correcte.
directives attribute is in the root of the JSON result.
Following APl documentation 
https://developer.amazon.com/es/docs/alexa-presentation-language/apl-render-document-skill-directive.html
directives attribute should be a part of the response attribute
* Jovo Framework version used: 2.0.2
=> Fix APL directives with v2

jovo-framework/src/middleware/Handler.ts, jovo-framework/test/handler.test.ts
This fixes an issue I encountered where the app would hang (and log an unhandled exception) if an intent immediately threw an exception. The root cause was using an async function as a Promise executor (more details here: https://eslint.org/docs/rules/no-async-promise-executor). There's no tslint rule yet for it unfortunately.
=> Fix for intent exception causing unhandled rejection

jovo-integrations/jovo-platform-alexa/src/response/visuals/ListTemplate1.ts, jovo-integrations/jovo-platform-alexa/src/response/visuals/ListTemplate2.ts, jovo-integrations/jovo-platform-alexa/test/modules/RenderTemplates.test.ts
For ListTemplate1 an image is optional for items, however Jovo was throwing a validation error if it was missing. This corrects that, while still preserving the validation for ListTemplate2 (which does require an image on items).
=> Image shouldn't be required for ListTemplate1

jovo-integrations/jovo-db-mysql/src/MySQL.ts
In some cases the UserID got cropped and the userData was not accessible anymore.
'userId: A string that represents a unique identifier for the user who made the request. The length of this identifier can vary, but is never more than 255 characters. The userId is automatically generated when a user enables the skill in the Alexa app.'
https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html
=> Set Field for primaryKey to 255 chars

docs/configuration/project-structure.md
Fix link to config.js doc.  It was pointed to project.js path.
=> Fix link to config.js doc

jovo-integrations/jovo-platform-alexa/src/modules/Display.ts, jovo-integrations/jovo-platform-alexa/test/modules/Display.test.ts
Related to my last PR, I also discovered that showVideo was causing session attributes to be dropped as well. This resolves it the exact same way, as well as adding a test to help verify its behavior when you inevitably refactor my fix :)
=> showVideo(...) should not drop session attributes

jovo-core/src/TestSuite.ts, jovo-integrations/jovo-platform-alexa/src/Alexa.ts, jovo-integrations/jovo-platform-alexa/src/core/AlexaRequestBuilder.ts, jovo-integrations/jovo-platform-alexa/src/core/AlexaResponseBuilder.ts, jovo-integrations/jovo-platform-alexa/src/core/Interfaces.ts, jovo-integrations/jovo-platform-alexa/src/index.ts, jovo-integrations/jovo-platform-dialogflow/src/Dialogflow.ts, jovo-integrations/jovo-platform-dialogflow/src/core/DialogflowRequestBuilder.ts, jovo-integrations/jovo-platform-dialogflow/src/core/DialogflowResponseBuilder.ts, jovo-integrations/jovo-platform-dialogflow/src/core/Interfaces.ts, jovo-integrations/jovo-platform-dialogflow/src/index.ts, jovo-integrations/jovo-platform-googleassistant/src/GoogleAssistant.ts, jovo-integrations/jovo-platform-googleassistant/src/core/GoogleAssistantRequestBuilder.ts, jovo-integrations/jovo-platform-googleassistant/src/core/GoogleAssistantResponseBuilder.ts, jovo-integrations/jovo-platform-googleassistant/src/core/Interfaces.ts, jovo-integrations/jovo-platform-googleassistant/src/index.ts
Made the TestSuite interface generic and created platform-specific sub-interfaces of it, with the purpose of making using platform-specific request/response methods easier in unit tests. Feel free to refactor anything I didn't do quite right! I think this'll also only work in Typescript 2.3+ (due to my usage of generic defaults), so if that's a problem feel free to reject this.
=> TestSuite is now generic, with platform-specific interfaces available

jovo-integrations/jovo-db-firestore/tsconfig.json
Fixes bug, where `jovo-db-firestore` module could not been found after installation.
The `outDir` option inside the `tsconfig.json` file was `./dist/src/` resulting in the wrong folder structure.
=>  🐛 Fixes bug where outDir was ./dist/src/ in `jovo-db-firestore`

jovo-integrations/jovo-platform-googleassistant/src/modules/GoogleAssistantCore.ts
On Google Assitant, displayText isn't display.
=> fix displayText not display

jovo-integrations/jovo-platform-alexa/src/Alexa.ts, jovo-integrations/jovo-platform-googleassistant/src/GoogleAssistant.ts
Calling setAlexaHandler/setGoogleAssistantHandler with a list of object won't fill correctly the handlers list.
Both function use _set to add handler in the handler list.
_set erase the previous list.
=> setAlexaHandler/setGoogleAssistantHandler don't works with a list of object.

jovo-integrations/jovo-platform-alexa/src/modules/AudioPlayerPlugin.ts
this.$alexaSkill.$audioPlayer.playerActivity isn't set.
the fix retrieve the status of the  player from the context.
=> fix missing playerActivity

jovo-integrations/jovo-cms-googlesheets/src/DefaultSheet.ts
Inside the `DefaultSheet.ts` the framework should reject a `JovoError` object instead of a string to log clearer error messages:
old:
```sh
Error -----------------------------------------------------------------
Code:
ERR_PLUGIN
Message:
Stack:
Error
at GoogleSheetsCMS.retrieveSpreadsheetData (C:\Users\kilic\_jovoWorkspace\test\node_modules\jovo-cms-googlesheets\src\GoogleSheetsCMS.ts:95:19)
at <anonymous>
Learn more:
https://www.jovo.tech/docs/cms/google-sheets
----------------------------------------------------------------------
----------------------------------------------------------------------
WARN: Jovo instance is not available. ON_ERROR doesn't work here
```
new:
```sh
Error -----------------------------------------------------------------
Code:
ERR_PLUGIN
Message:
sheet name …
```
=> ♻️ GoogleSheetsCMS integration should reject JovoError instead of string

jovo-integrations/jovo-platform-alexa/src/core/AlexaSkill.ts
fix getSelectedElementId return wrong value for APL TouchWrapper
=> fix getSelectedElementId return wrong value

jovo-core/src/SpeechBuilder.ts, jovo-core/test/speechbuilder.test.ts
Changes to SpeechBuilder's addText method to support arbitrary SSML elements. #431 
These changes simplify adding other helper methods for SSML syntax and allow users to add SSML supported by a specific platform even if Jovo hasn't been updated its API with helper methods.
I'd like feedback on if it would make sense for another argument to added to the other public methods as well, so a user could addSentence with some surrounding SSML tags.
=> Update addText to accept arbitrary SSML wrapping elements

docs/basic-concepts/requests-responses/response.md, jovo-integrations/jovo-platform-alexa/sample-response-json/v1/CountryPostalCardAsk.json, jovo-integrations/jovo-platform-alexa/sample-response-json/v1/FullAddressCardAsk.json, jovo-integrations/jovo-platform-alexa/sample-response-json/v1/LinkAccountCardAsk.json, jovo-integrations/jovo-platform-alexa/sample-response-json/v1/directives.json, jovo-integrations/jovo-platform-alexa/src/core/AlexaResponse.ts, jovo-integrations/jovo-platform-alexa/test/AlexaResponse.test.ts
add in more alexa response getters ported from Jovo V1. They include:
`hasAskForAddressCard()`
`hasAskForCountryAndPostalCodeCard()`
`hasLinkAccountCard()`
`hasStandardCard()`
`hasSimpleCard()`
`hasAplDirective()`
`hasDisplayDirective()` 
`hasAudioDirective()` 
`hasVideoDirective()` 
`getDirectives()`
`getAplDirective()`
`getDisplayDirective()` 
`getAudioDirective()` 
`getVideoDirective()`
- [X ] New feature (non-breaking change which adds functionality)
- [x ] My change requires a change to the documentation
- [x ] I have added tests to cover my changes
=> Add alexa res getters

jovo-integrations/jovo-db-datastore/src/DatastoreDb.ts, jovo-integrations/jovo-db-dynamodb/src/DynamoDb.ts, jovo-integrations/jovo-db-filedb/src/FileDb.ts, jovo-integrations/jovo-db-filedb/src/FileDb2.ts, jovo-integrations/jovo-db-firestore/src/Firestore.ts, jovo-integrations/jovo-db-mongodb/src/MongoDb.ts, jovo-integrations/jovo-platform-dialogflow/package-lock.json
The DB integrations saved `updatedAt` even if it was `undefined` which caused errors with Firestore. As it's generally not a good practice to save undefined values, the changes were made to every db integration.
You can find the issue here: [#472](https://github.com/jovotech/jovo-framework/issues/472)
=> 🐛 DB: Saves updatedAt only if it's defined

jovo-platforms/jovo-platform-alexa/src/core/AlexaRequest.ts
Added viewport interfaces for typescript + getAlexaDevice method, which gives back device description (according to alexaskill test page: small hub, large hub...)
=> Adding viewport info for alexaRequests

jovo-platforms/jovo-platform-dialogflow/src/DialogflowCore.ts
Currently in the Dialogflow plugin there is a discrepancy in the naming of the session attributed output context. The getter uses the config sessionId field, while the setter uses a hardcoded "_jovo_session_". I changed the setter to use the config field, and changed the config fields default from value from "session" to "_jovo_session_".
=> Fixed dialogflow session attributes issue

jovo-framework/src/server.ts
I upgraded to the latest version of jovo and suddenly nothing worked so I did some investigating and realised there was a mistake in the server.js. It was using the non-verified server in the verified server listen function so nothing with express worked.
=> Fixing a bug in server.js that breaks the express server

jovo-core/src/Extensible.ts
Currently when using Jovo in a typescript project the following error is thrown on compilation
`node_modules/jovo-core/dist/src/Extensible.d.ts(12,50): error TS2507: Type 'typeof internal' is not a constructor function type.`
This change prevents this type error. Projects and tests still run identically with this change.
=> EventEmitter typing issue

jovo-integrations/jovo-plugin-pulselabs/README.md, jovo-integrations/jovo-plugin-pulselabs/package.json, jovo-integrations/jovo-plugin-pulselabs/src/PulseLabs.ts
Currently the configuration options that can be passed to PulseLabs plugin accepts only apiKey. This change allows the user to pass additional configuration options like debug and timeout. Also passing integration type `Jovo`  to pulselabs SDK.
=> Added configuration options to PulseLabs plugin

jovo-platforms/jovo-platform-dialogflow/src/core/DialogflowRequest.ts
Calling getSessionAttribute on the initial request throws this error:
```
TypeError: Cannot read property 'find' of undefined
at DialogflowRequest.getSessionAttributes (/Users/zmorga386/projects/chuck/entrypoint/node_modules/jovo-platform-dialogflow/dist/src/core/DialogflowRequest.js:161:72)
```
This pr adds a fallback value of an empty array to all of the lodash get calls for outputContext in DialogflowRequest, and also fixes an incorrect find body.
=> Fixed Dialogflow Session Attributes Issues

jovo-core/src/Jovo.ts, jovo-core/test/Jovo.test.ts
Pass the input name being validated by a validator to the `parseForValidator` function.
Before this change, the function was raising an error due to the lack of `$input` parameters which cannot be passed via an intent redirect.
https://github.com/jovotech/jovo-framework/blob/0558d48d33779f3f560175e7ae20501b0f15540e/jovo-core/src/Jovo.ts#L653
Even if an intent is defined to receive an input parameter in the model definition,
it might be called via a redirect (e.g. `toIntent()`) which won't populate the `$input` object.
Therefore, it won't be possible to retrieve the input name from the `$input` object,
but it is available within the validation schema definition.
=> Fix: Prevent validators to fail after redirect

jovo-platforms/jovo-platform-alexa/src/index.ts, jovo-platforms/jovo-platform-alexa/src/modules/Display.ts
With this change it is possible to use an array of hints that will be shown using the `showHint` function like it is done with `addText`. Now this function accepts a string or an array of strings, this way extra dynamism is added to the Skill.
The declaration and definition of the function `showHint` had been changed to support either a simple string or an array of strings. The implementation had been taken from the `addText` one.
*Notes: Seems there are no previous tests for the current `showHint` implementation. Also seems that I can't update the documentation myself. Please, advice and thank you very much in advanced.*
=> :sparkles: Added support for random hints

docs/integrations/cms/airtable.md, jovo-integrations/jovo-cms-airtable/src/@types/airtable/index.d.ts, jovo-integrations/jovo-cms-airtable/src/AirtableCMS.ts, jovo-integrations/jovo-cms-airtable/src/DefaultTable.ts, jovo-integrations/jovo-cms-airtable/src/ResponsesTable.ts, jovo-integrations/jovo-cms-airtable/test/DefaultTable.test.ts, jovo-integrations/jovo-cms-airtable/tsconfig.json
🐛 Fixes empty cells being ignored when fetching data
The airtable.js library ignores empty cells of each record and doesn't provide their keys either. That resulted in the arrays being created from each record to be different in size, depending on the number of empty cells. To mitigate that, we now set the value of empty cells to be an empty string. That also fixes the issue of values being shifted to the wrong index.
🐛 Fixes bug with module's types and order of properties
The type bug prevented typescript projects using the integration from compiling. Besides that, Airtable API doesn't provide the table data in correct order, which this commit fixes by adding a config option called order, that allows the user to specify the order themselves. The framework handles that issue for the …
=>  🐛 Fixes multiple bugs of the Airtable integration

jovo-integrations/jovo-cms-airtable/src/AirtableCMS.ts
Fixes a bug in the airtable integration where the table keys were pushed for each page that was loaded instead of just once.
=> airtable multipage table bug fix

jovo-platforms/jovo-platform-dialogflow/src/DialogflowAgent.ts, jovo-platforms/jovo-platform-dialogflow/src/DialogflowCore.ts, jovo-platforms/jovo-platform-dialogflow/src/core/DialogflowRequest.ts
Currently the `isNewSession` method of a Dialogflow Agent is returning `true` for every request.
This fix will actually inspect the `outputContext` of the request to check whether the `_jovo_session_` context is present.
This will happen only when the `payload` doesn't contain an `isNewSession` method itself.
The fix should resolve #536
=> 🐛 Fix isNewSession for Dialogflow platform

jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/dialogflow/DefaultWelcomeIntent.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/dialogflow/HelpIntent.json, jovo-platforms/jovo-platform-dialogflow/src/core/DialogflowRequestBuilder.ts
This PR is adding two request samples to the DialogflowRequestBuilder used in the Test Suite.
It allows the Test Suite to invoke a launch intent or a generic intent when using a pure Dialogflow agent rather than an integration or GoogleAssistant.
Rather than amending the current `google` samples which are actually GoogleAssistent json requests, this PR is adding a new set for `dialogflow` which is the platform type returned by a pure Dialogflow agent.
This pr will fix #563
=> 🐛 Add request samples for Dialogflow requests

jovo-platforms/jovo-platform-googleassistant/package.json, jovo-platforms/jovo-platform-googleassistant/src/core/GoogleActionSpeechBuilder.ts, jovo-platforms/jovo-platform-googleassistant/test/GoogleActionSpeechBuilder.test.ts
This changeset adds tests for GoogleActionSpeechBuilder and fixes the following issues:
* wrong type declaration on url parameter
* when text is not given, assume empty text, don't substitute it by url
* crash when `url` is an array but `text` is not
* corrupt output when `url` is not an array but `text` is
* when text is empty, output XML-compliant self-closing tag (but this will mask away bug #583) as AlexaSpeechBuilder already does.
=> Fix GoogleActionSpeechBuilder.addAudio() to match docs+implementation+common sense

docs/integrations/databases/firestore.md, jovo-integrations/jovo-db-firestore/src/Firestore.ts
I ran into two issues when using the Firestore database integration when hosting the code in Firebase Cloud Functions:
1. I needed to use Firestore in my own code outside of the user data storage and retrieval since my application uses Firestore as a backend database as well. Because of that I had to initialize the firebase-admin and Firestore db before the DB integration. This caused an error because the initializeApp function on firebase-admin was being called twice. Once by my code and then again by the Firestore database integration.
2. Since I host my jovo project as a Firebase Cloud Function in the same project as Firestore database, I don't need to provide the databaseURL or credentials during the firebase-admin initialization. However the current Jovo Firestore database …
=> Updated Firestore database integration to accept an already initialized instance in the constructor

jovo-platforms/jovo-platform-alexa/src/modules/Display.ts
Update showVideo method to properly remove shouldEndSession property.
Since shouldEndSession is a boolean property, when the value was False it was not being removed from the output. Alexa does not accept shouldEndSession appearing at all on video responses.
=> fixed removing shouldEndSession in showVideo call

jovo-framework/src/index.ts, jovo-framework/src/middleware/Handler.ts
Added "active component" checks to `toStateIntent`, `toStatelessIntent` & `followUpState` to prevent leaving the conversational component handler when using those "state" related methods.
_Not sure if it can really be called a breaking change because component are still in development_
I don't think so, because from a user standpoint I assumed to stay inside my component when using states. 
All existing test are running fine for me
=> 💥✨Adjusted State Handling to prevent leaving active Conversational Components

docs/integrations/cms/google-sheets.md, jovo-integrations/jovo-cms-googlesheets/src/GoogleSheetsCMS.ts, jovo-integrations/jovo-cms-googlesheets/src/KeyObjectSheet.ts, jovo-integrations/jovo-cms-googlesheets/src/index.ts, jovo-integrations/jovo-cms-googlesheets/test/KeyObjectSheet.test.ts
This change adds a new spreadsheet type to the GoogleSheet CMS integration allowing a user to define sheets with 1 level nested objects.
See documentation for more info.
=> :sparkles: Add KeyObject sheet type to GoogleSheet CMS integration

docs/basic-concepts/routing/intents.md
If I understand correctly from [these docs](https://github.com/jovotech/jovo-framework/blob/0883d307d99351274f5bb54de08fc17ffc105b01/docs/getting-started/installation/v1-migration.md#L269), there is no longer any need to call `this.endSession` in the `END` event. This PR removes it from the docs.
=> Remove this.endSession in V2 docs on intents

jovo-framework/src/hosts/Lambda.ts
Currently, a `null` body-value will automatically cause ApiGateway to not be detected. This means the response will be sent back differently than expected. 
Additionally, the response-value should not get stringified except it's an object.
=> 🐛 Fixed Lambda-bug

jovo-framework/src/hosts/ExpressJS.ts
The ExpressJS-Host did not have any logic that would check if `fail` was called before `setResponse`, which was leading to the error that the log was spammed with something like `header were sent already`.
=> 🐛 Fixed ExpressJS bug

jovo-core/src/core/Platform.ts, jovo-integrations/jovo-asr-gcloud/src/GCloudAsr.ts, jovo-integrations/jovo-cms-googlesheets/src/GoogleSheetsCMS.ts, jovo-integrations/jovo-db-cosmosdb/src/CosmosDb.ts, jovo-integrations/jovo-db-mongodb/src/MongoDb.ts, jovo-integrations/jovo-nlu-dialogflow/src/DialogflowNlu.ts, jovo-integrations/jovo-tts-gcloud/src/GCloudTts.ts, jovo-platforms/jovo-platform-core/src/CorePlatform.ts, jovo-platforms/jovo-platform-twilioautopilot/src/Autopilot.ts
The `install`-method of `Extensible` has never been async, therefore the `setup` middleware should be used to initialize things asynchronously.
Always use the `setup`-Middleware for plugins to load data asynchronously.
=> ♻️ Refactored all async install methods

jovo-core/src/util/Log.ts
Mongo database was throwing errors and one of the parameters in error object was `code` which was of type `number`. Because of that function `addConsoleAppender` in `Log.js` file was throwing this exception: 
```
TypeError: msg.split is not a function
at Object.write (/../node_modules/jovo-core/dist/src/Log.js:135:45)
...
```
It was happening, because Number doesn't have `split` function, so I made sure that log event message is always of type `string`, by casting it.
After casting, I again was able to see exceptions thrown by my code,  instead of the one thrown by `addConsoleAppender` function.
=> 🐛 Added log event message cast to string

jovo-platforms/jovo-platform-facebookmessenger/src/FacebookMessenger.ts, jovo-platforms/jovo-platform-facebookmessenger/src/Interfaces.ts, jovo-platforms/jovo-platform-facebookmessenger/src/index.ts, jovo-platforms/jovo-platform-facebookmessenger/src/modules/FacebookMessengerCore.ts, jovo-platforms/jovo-platform-facebookmessenger/src/responses/Message.ts, jovo-platforms/jovo-platform-facebookmessenger/src/responses/messages/AttachmentMessage.ts
`FacebookMessenger` now has a `version` parameter for the config that determines which version of the Facebook-API should be used. By default `v6.0` will be used.
Additionally, an error was fixed that caused verification to fail due to a missing `pageAccessToken`.
The `pageAccessToken` is not needed for verification.
Related to #715
=> 🐛✨ Facebook Messenger - Improvements/Bugfixes

docs/platforms/google-assistant/visual.md
ON_ELEMENT_SELECTED() will not work unless you enable webhook fulfillment for your Default Fallback Intent. This should be added to the docs.
=> 📝Add info for ON_ELEMENT_SELECTED() to work

jovo-platforms/jovo-platform-alexa/src/index.ts, jovo-platforms/jovo-platform-alexa/src/modules/AskFor.ts
The following Alexa doc includes the isCardThrown as part of the Connections.Response:
[Send a Connections.SendRequest directive](https://developer.amazon.com/en-US/docs/alexa/smapi/voice-permissions-for-reminders.html#send-a-connectionssendrequest-directive)
=> Add getPermissionIsCardThrown

docs/advanced-concepts/components/using-components.md, e2e/test/component.test.ts, jovo-core/src/plugins/Component.ts, jovo-core/src/plugins/Handler.ts
Adds the ability to parse the `stateBeforeDelegate` property in the delegation options.
=> Components: parse stateBeforeDelegate in delegate()

jovo-clients/jovo-client-web-vue/src/JovoWebClientVue.ts
Moved `start` from constructor to a method. 
`start` of the plugin will have to be called before anything else.
Additionally, `start` is required to be called from a click-handler in order to properly work on Safari.
=> 🐛 Fixed bug related to JovoWebClientVue

jovo-platforms/jovo-platform-bixby/README.md, jovo-platforms/jovo-platform-bixby/src/core/BixbyCore.ts, jovo-platforms/jovo-platform-bixby/src/core/BixbyResponse.ts, jovo-platforms/jovo-platform-bixby/src/core/Interfaces.ts
Besides `_JOVO_SPEECH_` that contains SSML, the response needs to include text only for display. So, add `_JOVO_TEXT_` to the response.
Usage:
```
result-view {
match {
JovoResponse (response)
}
message {
if (exists(response._JOVO_TEXT_) && exists(response._JOVO_SPEECH_)) {
template("#{value (response._JOVO_TEXT_)}") {
speech ("#{value (response._JOVO_SPEECH_)}")
}
}
}
}
```
=> Add _JOVO_TEXT_ to return non SSML text

jovo-clients/jovo-client-web/src/components/request/RequestComponent.ts, jovo-platforms/jovo-platform-alexa/src/modules/AlexaCore.ts, jovo-platforms/jovo-platform-core/src/Interfaces.ts, jovo-platforms/jovo-platform-core/src/core/CorePlatformRequest.ts, jovo-platforms/jovo-platform-core/src/modules/CorePlatformCore.ts
`Alexa` now also checks if the `request`-object of the request has a `requestId` attribute.
Added a type to `CorePlatformRequest` for easier distinction.
=> 🐛 Fixed bug that would cause CorePlatformRequests to be handled by Alexa

docs/basic-concepts/routing/intents.md
The Intents page currently has a link pointing to a non-existent anchor for `Unhandled`. This PR points to the correct anchor
=> Correct link to Unhandled anchor on Intents page

jovo-platforms/jovo-platform-googlebusiness/README.md, jovo-platforms/jovo-platform-googlebusiness/package.json, jovo-platforms/jovo-platform-googlebusiness/src/services/GoogleBusinessAPI.ts
Replace the dependency `googleapis` with `google-auth-library`, because only a single export of the auth library is used.
Drastically reduces package size.
=> 🔥 Replace `googleapis` with `google-auth-library`

jovo-platforms/jovo-platform-facebookmessenger/src/responses/messages/AttachmentMessage.ts, jovo-platforms/jovo-platform-facebookmessenger/src/responses/messages/TextMessage.ts
The API threw an error if an empty quick_replies-array was sent.
Therefore, no quick-replies will be sent when the array is empty.
=> 🐛 Fix FacebookMessenger bug

jovo-platforms/jovo-platform-googlebusiness/src/GoogleBusiness.ts, jovo-platforms/jovo-platform-googlebusiness/src/Interfaces.ts, jovo-platforms/jovo-platform-googlebusiness/src/core/GoogleBusinessBot.ts, jovo-platforms/jovo-platform-googlebusiness/src/index.ts, jovo-platforms/jovo-platform-googlebusiness/src/modules/Cards.ts, jovo-platforms/jovo-platform-googlebusiness/src/modules/GoogleBusinessCore.ts, jovo-platforms/jovo-platform-googlebusiness/src/services/GoogleBusinessAPI.ts
The `GoogleBusiness`-platform is now capable of sending multiple responses asynchronously. 
Now, it is possible to answer with multiple messages to a single request.
- Implemented the method `showText` to immediately send a text message.
- ⚠️ Changed the behavior of `showCarousel` and `showStandaloneCard` to immediately send their respective rich-card.
Additionally, a method `setFallback` was implemented which allows setting a `fallback`-value for the response. For more information about the `fallback`-value, take a look [here](https://developers.google.com/business-communications/business-messages/guides/build/send#fallback_strategy).
=> ✨ Implement asynchronous responses for GoogleBusiness

jovo-platforms/jovo-platform-googlebusiness/README.md, jovo-platforms/jovo-platform-googlebusiness/src/GoogleBusiness.ts
[Google Business Messages sends multiple messages with the same `messageId`](https://developers.google.com/business-communications/business-messages/guides/learn/best-practices#check_for_duplicate_incoming_messages) if the response is not returned fast enough.
For example, this can happen in a Lambda when it warms up or if time-intensive api-calls are made.
In order to avoid handling a message twice, the `messageId` will be stored in the session-data of the user and checked for after setting the session-data.
> An immediate save is required because a Lambda may start multiple instances which then need to be aware of the requests of the other instance(s).
=> 🐛✨ Implement check for duplicated messages for GoogleBusiness

jovo-framework/src/middleware/user/JovoUser.ts, jovo-platforms/jovo-platform-googlebusiness/src/GoogleBusiness.ts, jovo-platforms/jovo-platform-lindenbaum/src/Lindenbaum.ts, jovo-platforms/jovo-platform-twilioautopilot/src/Autopilot.ts
The user-session-id gets only saved when it is defined.
Removed redundant loading of the session data from the user-session-data of `GoogleBusiness`, `Lindenbaum` and `Autopilot`.
The session-data will automatically be loaded by `JovoUser`.
=> 🐛 Fix saving of user-session-id

jovo-integrations/jovo-db-firestore/src/Firestore.ts
Firestore does not allow saving custom objects that were initialized with `new`. 
Therefore, when saving, instances have to be replaced by objects. This is done by using `JSON.parse` and `JSON.stringify`.
Related issue: #776
=> 🐛 Fix potential bug for Firestore

examples/javascript/05_facebookmessenger/attachments/src/app.js, examples/javascript/05_facebookmessenger/hello-world/src/app.js, examples/javascript/05_facebookmessenger/quick-replies/src/app.js, examples/javascript/05_facebookmessenger/sender-actions/src/app.js, examples/javascript/05_facebookmessenger/templates/src/app.js, examples/typescript/05_facebookmessenger/attachments/src/app.ts, examples/typescript/05_facebookmessenger/quick-replies/src/app.ts, examples/typescript/05_facebookmessenger/sender-actions/src/app.ts, examples/typescript/05_facebookmessenger/templates/src/app.ts, jovo-platforms/jovo-platform-facebookmessenger/README.md, jovo-platforms/jovo-platform-facebookmessenger/src/FacebookMessenger.ts, jovo-platforms/jovo-platform-facebookmessenger/src/Interfaces.ts, jovo-platforms/jovo-platform-facebookmessenger/src/core/MessengerBot.ts, jovo-platforms/jovo-platform-facebookmessenger/src/core/MessengerBotResponse.ts, jovo-platforms/jovo-platform-facebookmessenger/src/index.ts, jovo-platforms/jovo-platform-facebookmessenger/src/modules/FacebookMessengerCore.ts, jovo-platforms/jovo-platform-facebookmessenger/src/responses/Message.ts
Facebook Messenger allows sending multiple messages, therefore it makes sense to change the way the platform works to immediately send the request. 
⚠️ Breaking Changes:
- The signatures of the `show`-methods except for the quick-reply-related methods have changed to return a `Promise<AxiosResponse<SendMessageResponse>` instead of `MessengerBot`
- The message that is the result of calling `tell` or `ask` will now **always** be the **last** message to be sent.
=> ♻️ ✨ Refactor Facebook Messenger platform - asynchronous Responses

docs/basic-concepts/data/user.md, jovo-framework/src/middleware/user/JovoUser.ts
`dataKey` can be passed to the `SessionDataConfig` in order to change the key the data gets persisted for.\
This is helpful for MongoDB, because `$data` is not allowed as a key.
Related issue #833
=> ✨ Implement configurable user-session-data-key

jovo-clients/jovo-client-web/package.json, jovo-clients/jovo-client-web/src/Client.ts, jovo-clients/jovo-client-web/src/core/RepromptHandler.ts, jovo-clients/jovo-client-web/src/standalone/AudioPlayer.ts, jovo-clients/jovo-client-web/src/standalone/AudioRecorder.ts, jovo-clients/jovo-client-web/src/standalone/SpeechRecognizer.ts, jovo-clients/jovo-client-web/src/standalone/SpeechSynthesizer.ts, jovo-clients/jovo-client-web/src/standalone/Store.ts, jovo-clients/jovo-client-web/src/util/BrowserDetector.ts, jovo-clients/jovo-client-web/src/util/OSDetector.ts, jovo-clients/jovo-client-web/src/util/OSHelper.ts, jovo-clients/jovo-client-web/src/util/index.ts
- BrowserDetector uses [`detect-browser`](https://www.npmjs.com/package/detect-browser) to detect the used browser, a wrapper is written around the package to also catch the Brave-browser
- SpeechRecognizer now only is supported in Chrome because Chrome is the only browser that has fully implemented SpeechRecognition
- Added checks to Client and SpeechRecognizer that checks if it is supported by the current browser
- Renamed OSHelper to OSDetector and adjusted logic to work with BrowserDetector
=> ✨ Improve Web-Client browser-detection

jovo-integrations/jovo-plugin-debugger/package.json, jovo-integrations/jovo-plugin-debugger/src/JovoDebugger.ts, package-lock.json
Use `strip-ansi` to remove ANSI-codes from messages that are sent to the Jovo-Debugger.
Additionally, changed the way the message was built, now not only the first parameter of `console.log` is used but all instead.
=> ➕ Add `strip-ansi` to remove ANSI-codes from messages that are sent to the Jovo-Debugger

jovo-platforms/jovo-platform-googlebusiness/src/core/GoogleBusinessRequest.ts
Changed `getRawText` of `GoogleBusinessRequest` to return the `postbackData` of a `Suggestion` rather than the `text` and only the `text` if there is no `postbackData`.
=> ✨ Use postbackData of suggestions if possible

jovo-integrations/jovo-analytics-googleanalytics/README.md, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalytics.ts, jovo-integrations/jovo-analytics-googleanalytics/src/index.ts
Allows developers to provide specific Google Analytics parameters, and easily provide details for Google Optimize experiments. This is accomplished by adding the `$parameters` object to google analytics which is used when constructing the pageview parameters.
=> feat: add Google Optimize support

jovo-clients/jovo-client-web/index.html, jovo-clients/jovo-client-web/src/Client.ts, jovo-platforms/jovo-platform-core/src/CorePlatform.ts, jovo-platforms/jovo-platform-core/src/core/CorePlatformRequest.ts, jovo-platforms/jovo-platform-core/src/core/CorePlatformResponse.ts, jovo-platforms/jovo-platform-core/src/index.ts, jovo-platforms/jovo-platform-core/src/modules/CorePlatformCore.ts, jovo-platforms/jovo-platform-web/src/core/WebAppResponse.ts, jovo-platforms/jovo-platform-web/src/modules/WebPlatformCore.ts
Instead of parsing the audio-data in the `request`-middleware of `CorePlatform`, the parsing will now occur in the platform's respective core-module. This way we can assure that the parsing only happens if the request matches the platform.
closes #878
=> 🐛 Fix bug related to audio in the request for CorePlatform and WebPlatform 

jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsAlexa.ts
The used method $googleAnalytics.sendUserEvent sets the page parameter to the jovo route. For SkillEvent this is not a valid parameter. Used the event method instead.
=> Alexa Event Tracking on Google Analytics wrong pagename fix

jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalytics.ts, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsAlexa.ts, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsGoogleAssistant.ts
Send data before response + promisify.
Lambda environments skip async sending executions. In the next request the lambda tries to send them again. This can lead to runtime errors or missing data on the dashboard (depending on your lambda settings).
+ improve hint if config is missing 
fixes #837
=> Fix TLS Errors on Lambda

jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalytics.ts
Adding customParameters at the end of the return object will allow us to override  documentTitle/documentPath/documentHostName.
Add following command will override default page title by "MyIntentName"
this.$googleAnalytics.setParameter('documentTitle','MyIntentName');
=>  Google Analytics Allow overriding documentTitle/documentPath/documentHostName

docs/basic-concepts/data/user.md, jovo-framework/src/middleware/user/JovoUser.ts, jovo-framework/test/middleware/user/JovoUser.test.ts
This PR adds the sessionId of the request to the ContextPrevObject. A lot of times, the only past interactions of interest are the ones of the same session or a specific session. This adds this session context to the prev array. It also makes it easier to skip for the session irrelevant interactions. One Example would be Alexa Skill Events that happen in the middle of the session and therefore are added to the prev array in middle of all the session requests with no easy way to see, that this interaction was not part of the session. 
I guess this would require an update to the documentation for the user data (https://www.jovo.tech/docs/data/user). I could also add the documentation, if this feature is to be added.
=> ✨ added sessionId to ContextPrevObject

docs/output.md, framework/package.json, framework/src/BaseOutput.ts, framework/src/Jovo.ts
It is now possible to pass properties of `OutputTemplate` to `$send`, e.g.  `$send(SomeOutput, { message: 'Overwritten message' })` will result in an `OutputTemplate` with `message` set to 'Overwritten message'.
=> :sparkles: Implement passing of OutputTemplate-properties directly to `$send` via the options

jovo-platforms/jovo-platform-googleassistant/src/core/Interfaces.ts, jovo-platforms/jovo-platform-googleassistant/src/modules/InteractiveCanvas.ts, jovo-platforms/jovo-platform-googleassistant/src/response/HtmlResponse.ts, jovo-platforms/jovo-platform-googleassistantconv/src/core/Interfaces.ts
Google added `enableFullScreen` and `continueTtsDuringTouch` to the canvas object. This PR updates the existing `HtmlResponse` interfaces
=> :sparkles: Add enableFullScreen and continueTtsDuringTouch

integrations/db-filedb/src/FileDb.ts
Fix invalid path that was used in FileDB to initialize the db-folder
=> 🐛 Fix invalid path in FileDB

platforms/platform-facebookmessenger/src/MessengerBot.ts, platforms/platform-googlebusiness/src/GoogleBusinessBot.ts
Multiple `$send`-calls caused the output to be sent multiple times.
Only the output that was created by the respective `$send`-call is now sent.
=> 🐛 Fix bug caused by multiple `$send`-calls when using FacebookMessenger or GoogleBusiness

framework/src/Jovo.ts, framework/src/JovoSession.ts, framework/src/interfaces.ts, integrations/db-dynamodb/src/DynamoDb.ts, integrations/db-filedb/src/FileDb.ts
* PR fixes missing configuration delegation to the `setPersistableData` method
=> 🐛 Fix missing configuration in setPersistableData

framework/src/Jovo.ts, framework/src/JovoSession.ts, framework/src/interfaces.ts, integrations/db-dynamodb/.npmignore, integrations/db-dynamodb/README.md, integrations/db-dynamodb/jest.config.js, integrations/db-dynamodb/package.json, integrations/db-dynamodb/src/DynamoDb.ts, integrations/db-dynamodb/src/index.ts, integrations/db-dynamodb/test/dummy.test.ts, integrations/db-dynamodb/tsconfig.build.cjs.json, integrations/db-dynamodb/tsconfig.build.esm2015.json, integrations/db-dynamodb/tsconfig.build.esm5.json, integrations/db-dynamodb/tsconfig.build.types.json, integrations/db-dynamodb/tsconfig.json, integrations/db-filedb/src/FileDb.ts
The first implementation of the DynamoDb integration, it's still WIP and a few thing to discuss:
This integration requires different types of configuration properties in several places:
1.) Basic stuff like `tableName` for every load/save
2.) A configuration that is needed for table creation `readCapacityUnits`
3.) Configuration for the DynamoDB SDK provided by AWS `credentials`, `region` etc
Current solution:
```typescript
export interface DynamoDbConfig extends DbPluginConfig {
primaryKeyColumn?: string;
tableName?: string;
readCapacityUnits?: number;
writeCapacityUnits?: number;
dynamoDbClient?: DynamoDBClientConfig;
}
``` 
Very simple example (used in AWS Lambda)
```typescript
app.use(
new DynamoDb({
tableName: 'v4demo',
}),
);
```
Example for other environments:
```typescript …
```
=> ✨ Initial DynamoDb implementation (wip)

framework/src/index.ts, framework/src/plugins/RoutingExecutor.ts
- The `lastRouteMatchIndexWithPrioritizedOverUnhandled` was invalid due to being retrieved relative to the reversed array instead of the correctly ordered array
=> 🐛 Fix invalid index when setting `skip` in `RoutingExecutor`

framework/src/plugins/RoutingExecutor.ts
In #967 a check was forgotten, which checks if the reversed-index is smaller than 0.
This caused the whole routing-matches-list to be skipped. 
By adding the check, this can not occur.
=> 🐛 Fix missing check if the reverse-index is small than 0 in `RoutingExecutor`

framework/src/JovoSession.ts
`JovoSession` did directly take the passed `createdAt` from `data`. Now, a new Date object will be created based on the passed `data.createdAt`.
=> 🐛 Fix bug caused by passing a string `createdAt`-date

framework/src/Jovo.ts, framework/src/JovoDevice.ts, framework/src/JovoUser.ts, framework/src/Platform.ts, framework/test/utilities/platform.ts, platforms/platform-alexa/src/Alexa.ts, platforms/platform-alexa/src/AlexaDevice.ts, platforms/platform-alexa/src/AlexaPlatform.ts, platforms/platform-alexa/src/AlexaUser.ts, platforms/platform-core/src/Core.ts, platforms/platform-core/src/CoreDevice.ts, platforms/platform-core/src/CorePlatform.ts, platforms/platform-core/src/CorePlatformDevice.ts, platforms/platform-core/src/CorePlatformUser.ts, platforms/platform-core/src/CoreRequest.ts, platforms/platform-core/src/CoreUser.ts, platforms/platform-core/src/index.ts, platforms/platform-facebookmessenger/src/FacebookMessenger.ts, platforms/platform-facebookmessenger/src/FacebookMessengerDevice.ts, platforms/platform-facebookmessenger/src/FacebookMessengerPlatform.ts, platforms/platform-facebookmessenger/src/FacebookMessengerUser.ts, platforms/platform-googleassistant/src/GoogleAssistant.ts, platforms/platform-googleassistant/src/GoogleAssistantDevice.ts, platforms/platform-googleassistant/src/GoogleAssistantPlatform.ts, platforms/platform-googleassistant/src/GoogleAssistantUser.ts, platforms/platform-googlebusiness/src/GoogleBusiness.ts, platforms/platform-googlebusiness/src/GoogleBusinessDevice.ts, platforms/platform-googlebusiness/src/GoogleBusinessPlatform.ts, platforms/platform-googlebusiness/src/GoogleBusinessUser.ts
The correct types are now returned for platform-specific Jovo-instances.
Example:
`this.$alexa.$device` will return an `AlexaDevice`-instance and also have the correct type.
Before, type-hinting assumed a `JovoDevice` was returned.
=> 🏷️ ♻️ Refactor `Jovo`-typings

integrations/nlu-nlpjs/README.md, integrations/nlu-nlpjs/src/NlpjsNlu.ts
This fixes a bug that was caused by returning an array of `Entity` instead of an `EntityMap`.
=> 🐛 Fix bug that caused entities of `NlpjsNlu` to be set to an array instead of an `EntityMap`

docs/device.md, framework/src/JovoDevice.ts, platforms/platform-alexa/src/AlexaDevice.ts, platforms/platform-core/src/CoreDevice.ts, platforms/platform-facebookmessenger/src/FacebookMessengerDevice.ts, platforms/platform-googleassistant/src/GoogleAssistantDevice.ts, platforms/platform-googlebusiness/src/GoogleBusinessDevice.ts
Currently, device capabilities are defined as string types. This PR allows using enums as well. 
```typescript
import { Capability } from '@jovotech/framework';
// Example for one capability
if (this.$device.supports(Capability.Screen)) {}
// or 
if (this.$device.supports('SCREEN')) {}
```
Platform-specific:
```typescript
import { AlexaCapability } from "./AlexaDevice";
this.$device.supports(AlexaCapability.Apl)
// or
this.$device.supports('ALEXA:APL')
```
=> Improve type for device capabilities

platforms/platform-alexa/src/AlexaPlatform.ts
When changing the structure of the Alexa user event, the logic for setting entities from that data has not been updated.
Now `AlexaPlatform` will use the directly passed entity map instead of trying to build one.
=> 🐛 Fix logic for setting entities on Alexa user event

docs/app-config.md, docs/input.md, framework/src/App.ts, framework/src/Jovo.ts, framework/src/JovoInput.ts, framework/src/JovoRequest.ts, framework/src/plugins/RouterPlugin.ts, framework/src/plugins/RoutingExecutor.ts, platforms/platform-alexa/src/AlexaPlatform.ts, platforms/platform-googleassistant/src/GoogleAssistantPlatform.ts
- `nlu` and `asr` of `JovoInput` are now `undefined` by default.
- `nlu` of `JovoInput` is now only used by NLU-plugins and not platforms.
- `RouterPlugin` sets `intent` of `JovoInput` to the mapped intent if there is any and falls back to the intent otherwise. At this point, the `nlu.intent` of `JovoInput` will be used if there is no `intent` in the input.
- `RoutingExecutor` will look if the handler can handle the `type` of the input and otherwise looks if the handler can handle the `intent` of the input. At this point, it is also looked for `UNHANDLED`-handlers.
- Remove logic to overwrite `type` of the input in platforms.
- Smaller improvements
=> ♻️ Refactor input and routing

integrations/nlu-rasa/src/RasaNlu.ts
Bugfix
Switch from dot to index notation when filling entity map.
The variable entityAlias is not evaluated when using dot notation, which results in always having the key "entityAlias" as the only key in the entity map instead of having the actual entity names as keys
=> 🚑️ switched from dot to index notation when filling entity map.

docs/plugins.md, framework/src/Extensible.ts, framework/src/Middleware.ts, framework/src/NluPlugin.ts, framework/src/Platform.ts, framework/src/Plugin.ts, framework/src/plugins/BasicLogging.ts, framework/src/plugins/DbPlugin.ts, framework/src/plugins/HandlerPlugin.ts, framework/src/plugins/OutputPlugin.ts, framework/src/plugins/RouterPlugin.ts, integrations/db-dynamodb/src/DynamoDb.ts, integrations/db-filedb/src/FileDb.ts, integrations/nlu-snips/src/SnipsNlu.ts, integrations/plugin-debugger/src/JovoDebugger.ts, platforms/platform-alexa/src/AlexaPlatform.ts, platforms/platform-facebookmessenger/src/FacebookMessengerRequest.ts, platforms/platform-googleassistant/src/GoogleAssistantPlatform.ts, platforms/platform-googlebusiness/src/GoogleBusinessPlatform.ts, platforms/platform-googlebusiness/src/GoogleBusinessRequest.ts
- Refactor mounting to first register the plugin's config and then mount it
- Refactor middleware registering to only be called from within `mount`
- Arrow functions should not be used for middleware-functions
- Refactor `DbPlugin` to contain abstract methods
- Refactor logic in `BasicLogging` to persist start in `HandleRequest` instead of request-data
- Change input-type that is retrieved from the request for FacebookMessenger and GoogleBusiness
__Breaking Change:__ 💥 Classes that extend `Plugin` and use the parent's `MiddlewareCollection` will have to do that in `mount` and not `install`. Additionally, the function that is passed to the middleware should not be an arrow-function otherwise `this` will not reference the request-copy of the plugin. That means this update will only …
=> ♻️💥 Refactor middleware registering

docs/databases.md, framework/src/Jovo.ts, framework/src/JovoSession.ts, framework/src/JovoUser.ts, framework/src/Platform.ts, framework/src/interfaces.ts, framework/src/plugins/DbPlugin.ts, platforms/platform-facebookmessenger/README.md, platforms/platform-facebookmessenger/src/FacebookMessengerPlatform.ts, platforms/platform-googlebusiness/README.md, platforms/platform-googlebusiness/src/GoogleBusinessPlatform.ts
- The session data that is saved in the database now expires after a configurable amount of time. The default amount is 15 minutes.
- Platforms that do not have their own session data will by default enable the session data in the database in order to be able to use states and other session-related features. 
_Some of these changes are based on changes of #1015, therefore this should only be merged after #1015 was merged._
=> ✨♻️ Implement expiration of persisted session data as well as minor improvements to database plugins 

docs/handlers.md, framework/src/decorators/Intents.ts, framework/src/decorators/Platforms.ts, framework/src/decorators/Types.ts, framework/src/metadata/HandlerOptionMetadata.ts
The previous implementation caused the transpiled JS to not have a rest-parameter and therefore omit every argument after the first. Now a rest-parameter will always be assumed and the possible types that are passed are limited by overloaded signatures. In case an array is passed, some special treatment was necessary because the actual value will be an array inside the rest-parameter-array.
=> 🏷️ 🐛 Fix rest-parameters for decorators

framework/src/Platform.ts
`$platform` in `Jovo` was a reference to the platform instance that was passed in `use` or `plugins`.
Now, it will reference the mounted platform instead.
Using `this` in middleware-functions of platforms is no longer causing issues.
=> 🐛 Fix invalid reference of `$platform` in `Jovo`

docs/ridr-lifecycle.md, framework/src/HandleRequest.ts, framework/src/MiddlewareCollection.ts, platforms/platform-googlebusiness/src/GoogleBusinessPlatform.ts
Just like before, typing-indicator- and receipt-requests will be ignored, but now no further middlewares will be executed. This way the debugger for example will not log these requests.
Also improved `run` of `MiddlewareCollection` to check if the middleware exists after the `before.`-middleware has been executed. This way, removing middlewares in the `before.`-middleware allows skipping any further middlewares even the same middleware without the prefix.
=> 👔 Update logic to skip redundant requests for GoogleBusiness

integrations/db-dynamodb/src/DynamoDb.ts, integrations/db-dynamodb/src/index.ts
Fix a bug that was caused by cloning the `client`-property in `DynamoDb`.
During mounting a new client instance is now instantiated. This has the advantage that his `DynamoDBClient` will use the request-config.
Also added type-hinting for DynamoDb in config and plugins.
=> 🐛 Fix DynamoDb bug

docs/user.md, framework/src/JovoUser.ts, platforms/platform-alexa/src/AlexaUser.ts, platforms/platform-googleassistant/src/GoogleAssistantUser.ts
Adds `accessToken` property to `JovoUser` class + Implementations for `AlexaUser` and `GoogleAssistantUser`
`this.$user.accessToken` can be undefined or of type `string`. 
```typescript
LAUNCH() {
const accessToken = this.$user.accessToken;
return this.$redirect(LoveHatePizzaComponent);
}
```
In `v3` the `getAccessToken()` method was part of the abstract `JovoRequest` class.
=> ✨ Add accessToken property to JovoUser

docs/user.md, framework/src/JovoUser.ts, framework/src/plugins/DbPlugin.ts, framework/test/utilities/platform.ts, integrations/db-dynamodb/src/DynamoDb.ts, integrations/db-filedb/src/FileDb.ts, platforms/platform-alexa/src/AlexaUser.ts, platforms/platform-core/src/CoreUser.ts, platforms/platform-facebookmessenger/src/FacebookMessengerUser.ts, platforms/platform-googleassistant/README.md, platforms/platform-googleassistant/package.json, platforms/platform-googleassistant/src/GoogleAssistantPlatform.ts, platforms/platform-googleassistant/src/GoogleAssistantUser.ts, platforms/platform-googlebusiness/src/GoogleBusinessPlatform.ts, platforms/platform-googlebusiness/src/GoogleBusinessUser.ts
- Make `id` of `JovoUser` optional
- Only load and save data if `id` is defined
- Implement logic for Google Assistant to be able to use user data when the user's account is linked:
- the user-id is then persisted in `user.params._GOOGLE_ASSISTANT_USER_ID_` of the request-object
=> ♻️ Make `id` of `JovoUser` optional

docs/hooks.md, docs/jovo-properties.md, docs/output.md, docs/ridr-lifecycle.md, framework/src/Jovo.ts, framework/src/JovoHistory.ts, integrations/nlu-snips/src/SnipsNlu.ts, platforms/platform-facebookmessenger/src/FacebookMessenger.ts, platforms/platform-googlebusiness/src/GoogleBusiness.ts
Previously, `$output` of `Jovo` could either be an array of `OutputTemplate` objects or an `OutputTemplate` object. 
Now it can only be an `OutputTemplate` array. This change makes it easier to manipulate the output without having to check if it's an array or object all the time.
=> ♻️💥 `$output` is an array

docs/entities.md, framework/src/interfaces.ts, platforms/platform-alexa/README.md, platforms/platform-alexa/src/Alexa.ts, platforms/platform-alexa/src/AlexaRequest.ts, platforms/platform-alexa/src/interfaces.ts, platforms/platform-facebookmessenger/src/FacebookMessengerRequest.ts, platforms/platform-googleassistant/src/GoogleAssistant.ts, platforms/platform-googleassistant/src/GoogleAssistantRequest.ts, platforms/platform-googleassistant/src/interfaces.ts
- Refactor properties of `Entity`:
- `key` was renamed to `resolved`
- `id` is now the same value as `resolved` if nothing more fitting exists
- added `native` property for setting data that caused this entity to be set
- `$entities` is now typed for platforms that have a custom `Entity` like Alexa for example:
```
this.$alexa?.$entities?.foo // is of type AlexaEntity | undefined
```
=> ♻️💥 Refactor `$entities` 

jovo-integrations/jovo-analytics-googleanalytics/README.md, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalytics.ts, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsAlexa.ts, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsInstance.ts
When sending skill events and errors to google analytics there were situations where the lambda returned before finishing the calls. Result: hard error on next start.
I also changed two method names from "send*" to "enqueue*" because the methods did not send but enqueue.
=> :bug: google analytics skill events + error tracking fixed

framework/src/Jovo.ts
- Improved delegation to take into account when the currently delegating component is a global component.
- Global components usually do not get added to the state stack, but in order to delegate, a state is needed, therefore the global component is added to the stack when delegating but also immediately removed when resolving.
Closes #1049
=> 🐛 Fix a bug when delegating from a global component with a non-empty state

platforms/platform-googleassistant/src/GoogleAssistantPlatform.ts
Before a check for certain statuses was done. Instead, it is now only checked if there is any `slotFillingStatus` set.
=> 👔  Use selection intent if there is a `slotFillingStatus` 

jovo-integrations/jovo-cms-googlesheets/README.md, jovo-integrations/jovo-cms-googlesheets/src/DefaultSheet.ts, jovo-integrations/jovo-cms-googlesheets/src/GoogleSheetsCMS.ts, jovo-integrations/jovo-cms-googlesheets/src/ResponsesSheet.ts, jovo-integrations/jovo-cms-googlesheets/test/DefaultSheet.test.ts
Fixes access to public spreadsheets after deprecation of the Google Sheets API v3
https://cloud.google.com/blog/products/g-suite/migrate-your-apps-use-latest-sheets-api#which_version_of_the_api_should_be_used
Jovo apps using `public` spreadsheets have to update the code.
=> Fix/google sheets after API deprecation

integrations/plugin-debugger/docs/debugger-config.md, integrations/plugin-debugger/src/JovoDebugger.ts
This PR adjusts some minor details about the Jovo Debugger plugin. Since `debugger` is a reserved keyword, we'll have to use `debuggerConfig` in `jovo.debugger.js` instead.
=> :recycle: Adjust Jovo Debugger plugin

framework/package.json, framework/src/I18Next.ts, framework/src/Jovo.ts, package.json
Previously, if a path was passed that could not be found, the assumed type was TFunctionResult, now it is string like expected. In case the return type has to be casted, it can be done by manually passing the desired type as first generic parameter.
ts-toolbelt also had to be downgraded due to changes in F.AutoPath that caused the last part of a path to not be shown in auto-completion.
=> 🐛🏷️ Fix typing bug that caused $t method to not work as intended

output/output-googleassistant/README.md, platforms/platform-googleassistant/docs/scenes.md, platforms/platform-googleassistant/src/GoogleAssistantHandles.ts, platforms/platform-googleassistant/src/index.ts, platforms/platform-googleassistant/src/output/NextSceneOutput.ts
Add `NextSceneOutput` and `GoogleAssistantHandles.onScene(name: string)` helper
Usage:
```typescript
export class GlobalComponent extends BaseComponent {
LAUNCH() {
return this.$send(NextSceneOutput, { name: 'CollectionScene' });
}
@Handle(GoogleAssistantHandles.onScene('CollectionScene'))
handleCollectionScene() {
return this.$send({ message: 'hello' });
}
}
```
=> :sparkles: Add NextScene output, onScene GoogleAssistantHandle

common/package.json, common/src/JovoLogger.ts, integrations/plugin-debugger/package.json, integrations/plugin-debugger/src/JovoDebugger.ts
This PR removes the table view of the project name and the Jovo Debugger url + prevent logging undefined properties in context object.
=> Remove table view on `jovo run` + undefined properties in logger

integrations/plugin-debugger/src/JovoDebugger.ts, integrations/plugin-debugger/src/MockServer.ts, integrations/plugin-debugger/src/enums.ts
- The socket of the JovoDebugger plugin is now directly connected to the webhook and directly accepts requests from there
=> 🐛 Fix missing connection to webhook after CLI changes
