jovotech/jovo-framework

.eslintrc.json, .travis.yml, lib/integrations/analytics/analytics.js, lib/platforms/alexa/alexaResponse.js, lib/platforms/alexa/alexaSkill.js, lib/platforms/googleaction/googleAction.js, lib/platforms/googleaction/googleActionResponse.js, package.json, test/platforms/testJovo.js, test/tests.js
[Lodash](https://lodash.com/docs/4.17.4) is a really useful library to handle many kind of operations. In this case, it helps to set and get values from an object given a whole/fully specified path.
This PR also includes:
- Fixed some typos
- Fixed some eslint issues
=> Added lodash to handle set and get session attributes methods

.eslintrc.json, lib/integrations/db/dynamoDb.js, lib/jovo.js, lib/platforms/alexa/alexaRequest.js, lib/platforms/alexa/alexaSkill.js, lib/platforms/googleaction/googleAction.js, test/platforms/testJovo.js
In the [Amazon Alexa SDK](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/DynamoAttributesHelper.js#L63) the attribute name for storing user's information is called `mapAttr`. In the jovo framework the parameter is called `data`. So, to avoid existing skills/actions to break, and for developers to migrate their skills to Jovo, I created a method so that developers set the name of this parameter by themselves like this:
`app.setDynamoDbKey('mapAttr');`
=> ⚡️ Some DynamoDB improvements

lib/integrations/analytics/analytics.js
See issue #4 for more information.
=> :sparkles: Added skipUsers method for analytics integrations

lib/jovo.js, lib/platforms/alexa/alexaRequest.js, lib/platforms/alexa/alexaSkill.js, lib/platforms/googleaction/googleAction.js, lib/platforms/googleaction/googleActionRequest.js
This returns the timestamp from the individual platform's requests.
=> :sparkles: Added getTimestamp()

lib/jovo.js, lib/platforms/alexa/alexaRequest.js, lib/platforms/alexa/alexaSkill.js, lib/platforms/googleaction/googleAction.js, lib/platforms/googleaction/googleActionRequest.js
Returns true if user started a new session, false if request is part of an ongoing session.
=> :sparkles: Added isNewSession() for both platforms

docs/04_integrations/README.md, examples/indexAnalyticsIntegration.js, index.js, lib/integrations/analytics/analytics.js, lib/jovo.js, package-lock.json, package.json
* Add bespoken analytics to jovo-framework
* Bespoken analytics documentation
=> Bespoken analytics integration

lib/jovo.js
See this issue: https://github.com/jovotech/jovo-framework-nodejs/issues/28
=> ✨ Added NEW_USER and NEW_SESSION standard intents

docs/04_platform-specifics/amazon-alexa/README.md, docs/04_platform-specifics/amazon-alexa/dialog.md
Also renamed Dialog Mode to Dialog Interface to match the official documentation
=> 📝 Dialog interface docs & fixed typos

docs/02_app-configuration/README.md, docs/02_app-configuration/models/README.md, docs/02_app-configuration/server/README.md, docs/02_app-configuration/server/aws-lambda.md, docs/02_app-configuration/server/webhook.md
There are still dead links. I will add these, after I restructured the whole docs.
Alexa Verifier is still untouched.
=> 📝 WIP: App Configuration updated to the new Jovo app structure

README.md, docs/04_app-logic/01_routing/README.md, docs/04_app-logic/README.md, docs/05_platform-specifics/amazon-alexa/README.md, docs/05_platform-specifics/amazon-alexa/visual.md
created visual.md (video, cards, templates) in platform_specifics/amazon-alexa/ 
added platform-handlers to app-logic
switched to relative links on repo-readme
=>  📝 relative links | visual.md | platform-handler

lib/platforms/alexaSkill/alexaSkill.js
=> 🔨 Update alexaSkill.js

docs/02_cli/README.md, docs/04_app-logic/02_data/user.md, docs/04_app-logic/03_output/speechbuilder.md
Added Dialogflow V2 API support to the CLI docs
=> CLI doc update | getLocale() | speechBuilder().toString()

lib/app.js, lib/integrations/db/datastore.js, lib/integrations/db/db.js, lib/integrations/db/filePersistence.js, lib/integrations/db/filePersistenceV2.js, test/integrations/testDatastore.js, test/integrations/testDb.js, test/integrations/testFilePersistence.js, test/platforms/testBaseApp.js
...with some other improvements regarding db:
- Fixed bugs in FilePersistance
- Easy integration adding in db
=> Added gcloud datastore integration 

lib/app.js, lib/platforms/googleaction/googleActionResponse.js
- Import config object from app.json
- Add an additional check (issue #130)
=> :sparkles: Import config from app.json

examples/README.md, lib/app.js
=> Azure Functions: only accept request by POST method

docs/04_app-logic/01_routing/README.md
=> :memo: replace ” with " for doc-parser

README.md, docs/06_integrations/analytics/README.md, docs/README.md
Removed VoiceLabs as an analytics integration from the docs.
Added staging, plugins and testing to the main README of the repo as well as the main README of the docs.
=> 📝 removes voicelabs from docs ; adds staging, plugins, testing to advanced features

examples/alexa_specific/appAlexaDeviceAddress.js
The sample code for [alexa device address](https://github.com/jovotech/jovo-framework-nodejs/blob/master/examples/alexa_specific/appAlexaDeviceAddress.js) using jovo is broken, updated with the correct sample.
=> Sample code rectified the getAddress to getDeviceAddress

lib/platforms/googleaction/request/dialogFlowV2Request.js
Testing from within Dialogflow (V2) currently fails if platform specific features are used (like suggestion chips). This PR fixes this by copying all _workaround methods_ from the V1 implementation.
=> Fix testing from within Dialogflow V2

lib/platforms/alexaSkill/request/connectionsResponseRequest.js
Adds `getToken()` to retrieve the token used to resume the skill where it left off before the transaction.
=> ✨ Adds getToken() to connectionsResponseRequest

docs/05_platform-specifics/amazon-alexa/visual.md, lib/platforms/alexaSkill/alexaResponse.js, lib/platforms/alexaSkill/alexaSkill.js, package-lock.json, test/platforms/alexa/testAlexaResponse.js
Add the ability for Alexa to read a preamble message before starting a video by adding a fourth parameter to the `showVideo()` method:
Original method:
```javascript
this.alexaSkill().showVideo('https://www.url.to/video.mp4', 'Any Title', 'Any Subtitle');
```
Optional preamble:
```javascript
this.alexaSkill().showVideo('https://www.url.to/video.mp4', 'Any Title', 'Any Subtitle', 'Get ready to watch your video!');
```
=> Add Alexa Video Preamble Option

lib/app.js, lib/jovo.js, lib/platforms/alexaSkill/alexaResponse.js, lib/platforms/alexaSkill/alexaSkill.js, lib/platforms/alexaSkill/request/canFulfillIntentRequest.js, lib/platforms/alexaSkill/request/util/requestParser.js, lib/routing.js, lib/util.js
Added new Amazon Alexa feature: CanFulfillIntentRequest
Refer to the docs here:
https://developer.amazon.com/docs/custom-skills/understand-name-free-interaction-for-custom-skills.html#response-to-canfulfillintentrequest
=> ✨  Add CanFulfillIntentRequest

lib/platforms/alexaSkill/response/renderTemplate/bodyTemplate6.js, package-lock.json, test/platforms/alexa/testRenderTemplates.js
for body template 6 we need to setBackgroundImage instead setImage.
Testing this with echo Spot, and echo Show - it works!
=> fix body template 6

docs/03_app-configuration/README.md
=> 📝Update app config docs

docs/07_advanced/unit-testing/README.md
Add documentation for method `setAccessToken` in unit-test
issue: #207 
- [] My change requires a change to the documentation
=> Added Documentation For setAccessToken Method

docs/03_app-configuration/01_models/README.md
Update of the documentation according to the issue : [211](https://github.com/jovotech/jovo-framework-nodejs/issues/211)
=> Update readme with isList parameter for input

docs/05_platform-specifics/google-assistant/media-response.md
Add information about how to use option field according to the Google Media Response.
Documentation updated.
=> Media response option field

docs/03_app-configuration/01_models/README.md
Modify dialogflow priority parameter and declare possible values
=> Dialogflow priority

docs/03_app-configuration/01_models/README.md
Input Types allow automated expension on Dialogflow Entities
=> Input Types allow automated expension

docs/05_platform-specifics/google-assistant/visual.md, examples/google_action_specific/appGoogleAssistantCards.js, lib/platforms/googleaction/googleAction.js, lib/platforms/googleaction/googleActionResponseV2.js, test/platforms/googleaction/testGoogleActionResponse.js
I'm developing a voice app with Jovo and wanted a Google rich response that includes the new [Table card](https://developers.google.com/actions/assistant/responses#table_card). The[ Jovo contribute page](https://www.jovo.tech/contribute) lists "Table Card" as the first bullet under "Add Google Action Features", so I decided to try adding this new feature myself.
Please verify that all steps of the checklist are fully complete.
=> Add Table Card

docs/05_platform-specifics/README.md, docs/05_platform-specifics/amazon-alexa/README.md, docs/05_platform-specifics/amazon-alexa/data.md
Added docs on how to retrieve alexa skill contact information (name, email, mobile number) via the Alexa Contact Permissions API.
=> 📝 Adds alexas contact information docs

docs/02_cli/README.md
Correcting the spelling of 'folder'.
Update docs.
=> Update app config docs

examples/azure_functions/webhook/index.js, lib/app.js, lib/jovo.js
This addresses a few issues in Azure Functions support related to error handling:
- Any unhandled exception thrown by app or framework code would cause the function to hang, due to context.done not being called.
- If the file persistence provider couldn't create db.json (which would happen when an Azure Function was run using Run From Package enabled, which makes the filesystem read-only), due to a bug in promise handling in `Jovo.loadUserDataOnRequest` the app would hang due to the promise never being resolved or rejected.
- Added a warning as well as comments in the Azure Functions example around using file persistence in Azure Functions and how to disable it.
=> Azure Functions error handling fixes

lib/platforms/googleaction/googleAction.js, lib/platforms/googleaction/googleActionResponseV2.js, package-lock.json
During signin, we should be able customize the signin question. (I need to link your account to Google.) 
Link to the google SDK: 
https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/src/service/actionssdk/conversation/question/signin.ts
=> add context during signin.

docs/04_app-logic/01_routing/README.md
Added a link to the updated documentation for Dialogflows built-in intents. 
- [ x] My change requires a change to the documentation
=> Built in intents link for DialogFlow

lib/jovo.js, lib/tools/testSuite.js, test/platforms/testJovo.js
This fixes a couple bugs around exception processing during webhook requests.
=> Fix for webhook exception handling during unit tests

lib/platforms/alexaSkill/alexaSkill.js
Added a fallback API string to alexSkill.
Changed progressiveResponse to use internal getApiEndpoint function containing the fallback instead of directly accessing the request.
[Original Issue](https://github.com/jovotech/jovo-framework-nodejs/issues/260#issue-367542568
)
=> Alexa's submission process fails due to missing apiEndpoint on dummy request

lib/platforms/googleaction/googleAction.js, lib/platforms/googleaction/googleActionResponseV2.js
method ```addAskForNotificationPermission``` created using method ```addAskForPermission``` as example
=> Add functional of asking user for permission to send push notifications and getting existing permissions

lib/platforms/alexaSkill/alexaSkill.js
Add 'Alexa.Presentation.APL.UserEvent' to the list of request types in getRequestType(), do the same as 'Display.ElementSelected'
=> Add support for APL-based touch

lib/platforms/alexaSkill/alexaUser.js
Adds `getReminder()` to retrieve a single reminder from the API. Currently you can only retrieve all of them.
=>  ✨ Adds getReminder() to AlexaUser.js

README.md, docs/05_platform-specifics/amazon-alexa/README.md, docs/05_platform-specifics/amazon-alexa/audioplayer.md
Adds Playback Controller to feature list
Adds expected token and playbackFailed and improves formatting of audioplayer.md
=>  📝 AudioPlayer Docs

lib/platforms/googleaction/googleActionSpeechBuilder.js
At the beginning of a speech builder if you use directly .addAudio() like this : 
let speech = this.speechBuilder().addAudio("mp3_url") 
without text parameter, you will have an "undefined" on your phone screen on Google Assistant App.
Adding optional text will correct that.
=> Removing "undefined" on phone

lib/platforms/alexaSkill/alexaUser.js
When an error occurs we should stop the code sequence to return the error with reject(). In this issue, the code continued executing and it eventually threw the exception the reject was accounting for.
=> Added return statement after some reject(error)

jovo-framework/src/App.ts
=> 🐛 Fixes: Plugin config couldn't be added in config.js

docs/configuration/project-js.md
=> :memo: Update project.js Docs

docs/basic-concepts/routing/states.md
word missing, plural/ singular mix deleted
=> :memo: Update Docs states.md

docs/basic-concepts/model/README.md
=> :memo: Update README.md

docs/basic-concepts/output/README.md
=> :memo: Update Docs Output

docs/basic-concepts/model/platforms/README.md
=> 📝 Update README.md

docs/integrations/databases/mysql.md
Had some reference to Google Cloud Datastore.
I updated the text to cover the subject MySQL.
=> Removed Typo

README.md
Just went to check out the contributing page and noticed the link was broken. Cheers!
=> Update CONTRIBUTING.md badge link

jovo-integrations/jovo-platform-alexa/src/services/AlexaReminder.ts
If the user has not granted permission for notifications the API returns a 401 (403 is a MAX_REMINDERS_EXCEEDED).
https://developer.amazon.com/de/docs/smapi/alexa-reminders-api-reference.html#error-messages
=> Wrong response.httpStatus & Typo removed

README.md, docs/integrations/databases/README.md, docs/integrations/databases/cosmosdb.md, jovo-integrations/jovo-db-cosmosdb/.npmignore, jovo-integrations/jovo-db-cosmosdb/LICENSE, jovo-integrations/jovo-db-cosmosdb/README.md, jovo-integrations/jovo-db-cosmosdb/package-lock.json, jovo-integrations/jovo-db-cosmosdb/package.json, jovo-integrations/jovo-db-cosmosdb/src/CosmosDb.ts, jovo-integrations/jovo-db-cosmosdb/src/index.js, jovo-integrations/jovo-db-cosmosdb/src/index.ts, jovo-integrations/jovo-db-cosmosdb/test/dummy.test.ts, jovo-integrations/jovo-db-cosmosdb/tsconfig.json, jovo-integrations/jovo-db-cosmosdb/tslint.json
Adds Azure Cosmos DB integration, which just uses the existing MongoDB integration.
=> ✨ Adds Azure Cosmos DB integration

jovo-core/src/ActionSet.ts, jovo-core/src/Extensible.ts, jovo-core/src/Jovo.ts, jovo-core/src/Log.ts, jovo-framework/gulpfile.js, jovo-framework/src/App.ts, jovo-framework/src/index.ts, jovo-framework/src/middleware/Handler.ts, jovo-framework/src/middleware/Router.ts, jovo-framework/test/config.test.ts, jovo-framework/test/handler.test.ts, jovo-framework/test/router.test.ts, jovo-integrations/jovo-cms-googlesheets/src/ResponsesSheet.ts, jovo-integrations/jovo-platform-alexa/src/Alexa.ts, jovo-integrations/jovo-platform-alexa/src/core/AlexaSkill.ts, jovo-integrations/jovo-platform-alexa/src/modules/DialogInterface.ts, jovo-integrations/jovo-platform-alexa/test/modules/AlexaNLU.test.ts, jovo-integrations/jovo-platform-dialogflow/src/DialogflowAgent.ts, jovo-integrations/jovo-platform-googleassistant/src/GoogleAssistant.ts, jovo-integrations/jovo-platform-googleassistant/src/core/GoogleAction.ts
- Refactored handler core to provide a request-specific (Alexa handler, GoogleAssistant handler) handler execution
- Fix log level conversion `process.env.JOVO_LOG_LEVEL = 'verbose'`
- Fix `hasSlotValue(key)` bug in Alexa dialog interface
- Fix GoogleSheets multiple responses sheets bug
- Update gulp file to version 4
=> New handler

README.md, docs/integrations/databases/README.md, docs/integrations/databases/cosmosdb.md, docs/integrations/databases/firestore.md, docs/nav.json, jovo-integrations/jovo-db-firestore/.npmignore, jovo-integrations/jovo-db-firestore/LICENSE, jovo-integrations/jovo-db-firestore/README.md, jovo-integrations/jovo-db-firestore/package-lock.json, jovo-integrations/jovo-db-firestore/package.json, jovo-integrations/jovo-db-firestore/src/Firestore.ts, jovo-integrations/jovo-db-firestore/src/index.js, jovo-integrations/jovo-db-firestore/src/index.ts, jovo-integrations/jovo-db-firestore/test/dummy.test.ts, jovo-integrations/jovo-db-firestore/tsconfig.json, jovo-integrations/jovo-db-firestore/tslint.json
Adds Google Firestore integration.
=> ✨ Adds Google Firestore integration

jovo-framework/src/index.ts
Adds missing `GoogleCloudFunction` export to `jovo-framework/src/index.ts`
=> 🐛 Adds GoogleCloudFunction export

docs/workflows/cli/deploy.md
Existing command is incorrect and produce error: "use correct syntax".
=> 📝 Fix typo

docs/basic-concepts/requests-responses/README.md
=> Links are now working.

docs/basic-concepts/requests-responses/README.md
=> updated links

docs/platforms/amazon-alexa/data.md
=> Removed old example code

docs/platforms/google-assistant/visual.md
=> Updated Links to Samples

jovo-integrations/jovo-platform-googleassistant/src/modules/Cards.ts
=> Typo removed

docs/testing/unit-testing.md
=> 📝 Fixes broken link

jovo-integrations/jovo-db-firestore/package.json, jovo-integrations/jovo-db-firestore/src/Firestore.ts
Refactored according to code review with @aswetlow
=> 👌 jovo-db-firestore refactor

docs/platforms/amazon-alexa/audioplayer.md
=> Style guide & Typo removed.

jovo-integrations/jovo-platform-alexa/src/Alexa.ts, jovo-integrations/jovo-platform-alexa/src/index.ts, jovo-integrations/jovo-platform-alexa/src/modules/ProactiveEvent.ts, jovo-integrations/jovo-platform-alexa/src/services/AlexaAPI.ts
=> ✨ Adds Alexa Proactive Event API

examples/01_alexa/proactive-events-api/package.json, examples/01_alexa/proactive-events-api/src/app.js, examples/01_alexa/proactive-events-api/src/config.js, examples/01_alexa/proactive-events-api/src/index.js, jovo-integrations/jovo-platform-alexa/src/modules/ProactiveEvent.ts
=> ✨ Adds param to sendEvent() to switch between live and dev url || Adds example to examples folder

CHANGELOG.md
=> Missing Kaan :-(

jovo-core/package-lock.json, jovo-core/package.json, jovo-core/src/BaseApp.ts, jovo-core/src/Log.ts, jovo-framework/package.json, jovo-framework/src/hosts/AzureFunction.ts
This change enhances the AzureFunctions host to add a custom appender when activated that writes logs to `context.log` instead of `console.log`, allowing them to be associated with individual requests in the Azure Portal. In order to accomplish that I needed to make some medium-sized changes to Log and add a new package (asyncctx) to give appenders access to the request (Host) object.
Very much open to feedback/changes!
CC @aswetlow
=> Implemented Azure Functions context logging

docs/platforms/amazon-alexa/data.md, examples/01_alexa/geolocation/package.json, examples/01_alexa/geolocation/src/app.js, examples/01_alexa/geolocation/src/config.js, examples/01_alexa/geolocation/src/index.js, jovo-integrations/jovo-platform-alexa/src/core/AlexaRequest.ts, jovo-integrations/jovo-platform-alexa/src/index.ts, jovo-integrations/jovo-platform-alexa/src/modules/Cards.ts, jovo-integrations/jovo-platform-alexa/src/response/visuals/AskForLocationPermissionsCard.ts, jovo-integrations/jovo-platform-alexa/test/modules/Cards.test.ts
=> ✨ Adds Alexa Geolocation support (also known as Location Services)

docs/platforms/amazon-alexa/data.md, examples/01_alexa/geolocation/src/app.js, jovo-integrations/jovo-platform-alexa/src/core/AlexaRequest.ts, jovo-integrations/jovo-platform-alexa/src/core/AlexaSkill.ts
=> 👌 Adds geolocation interface to $alexaSkill

docs/platforms/google-assistant/README.md, docs/platforms/google-assistant/data.md, jovo-integrations/jovo-platform-googleassistant/src/modules/AskFor.ts
Adds missing `ON_DATETIME` intent and adds `askForDateTime` and `askForConfirmation` to the docs.
=> 🐛 Adds missing ON_DATETIME intent | 📝 Adds askForDateTime & askForConfirmation

README.md, docs/nav.json, docs/platforms/amazon-alexa/README.md, docs/platforms/amazon-alexa/pay.md, jovo-integrations/jovo-platform-alexa/src/core/AlexaRequest.ts, jovo-integrations/jovo-platform-alexa/src/core/AlexaSkill.ts, jovo-integrations/jovo-platform-alexa/src/index.ts, jovo-integrations/jovo-platform-alexa/src/modules/Cards.ts, jovo-integrations/jovo-platform-alexa/test/modules/Cards.test.ts
Adds helper methods for Amazon Pay:
Check the permission status using `getAmazonPayPermissionStatus()`, `isAmazonPayPermissionGranted()`, and `isAmazonPayPermissionDenied()`. 
Send a permission card to ask the user to grant the amazon pay permission: `showAskForAmazonPayPermissionCard()`.
=> ✨📝Adds Amazon Pay helper methods and docs

docs/workflows/cli/README.md
=> removed init command (of v1)

docs/platforms/google-assistant/data.md, docs/platforms/google-assistant/notifications.md, examples/02_googleassistant/ask-for-x/src/app.js, jovo-integrations/jovo-platform-dialogflow/sample-request-json/v2/google/OnPlace.json, jovo-integrations/jovo-platform-dialogflow/src/core/DialogflowRequestBuilder.ts, jovo-integrations/jovo-platform-googleassistant/src/index.ts, jovo-integrations/jovo-platform-googleassistant/src/modules/AskFor.ts, jovo-integrations/jovo-platform-googleassistant/test/AskFor.test.ts
- `askForPlace` didn't map the parameters to the correct attributes
- The built-in intent to map the response for the `askForPlace` helper was missing. Added that (`ON_PLACE`)
- Added a helper to access the place object which contains the address the user was prompted for
- Added tests for `askForPlace()` and `getPlace()`
- Added all of that to the docs
- Added `askForPlace()` to the examples folder `ask-for-x`
=> Fixes askForPlace(), adds helper, tests and docs

jovo-core/src/errors/JovoError.ts
The `JovoError.ts` class didn't log the module, which is fixed in this PR
=> 🐛 Fixes: JovoError doesn't print module

jovo-integrations/jovo-platform-googleassistant/src/GoogleAssistant.ts
=> fix  Google Assistant handler not merge correctly

jovo-integrations/jovo-db-mysql/src/MySQL.ts
=> Increased storage to MEDIUMTEXT

docs/integrations/databases/firestore.md
Adds explanation from #418 to docs
=> 📝 Adds infos for Firestore on AWS Lambda

docs/configuration/hosting/express-js.md
=> added missing config for alexa verified endpoint

docs/platforms/amazon-alexa/audioplayer.md
update audio player doc to jovo 2.x syntax
=> Update deprecated code

jovo-integrations/jovo-cms-i18next/test/i18next.test.ts
=> :white_check_mark: Update I18Next Tests

jovo-integrations/jovo-cms-i18next/src/I18Next.ts, jovo-integrations/jovo-cms-i18next/test/i18next.test.ts
=> :recycle: Fix I18Next TsLint issues

docs/platforms/amazon-alexa/in-skill-purchases.md
=> IntentName is Cancel instead of Refund

jovo-core/src/User.ts, jovo-framework/src/index.ts, jovo-framework/src/middleware/user/JovoUser.ts
Stores the last state of the db in hashed form inside the $user object and compare it to the hashed current state inside `saveDb()` and only save the current state to the db if it differs from the last.
Also replaces `Error` with `JovoError`.
=> ⚡️ DB save optimization only saves to db if changes were made

jovo-core/src/Interfaces.ts, jovo-framework/src/middleware/user/JovoUser.ts, jovo-integrations/jovo-db-datastore/src/DatastoreDb.ts, jovo-integrations/jovo-db-dynamodb/src/DynamoDb.ts, jovo-integrations/jovo-db-filedb/src/FileDb.ts, jovo-integrations/jovo-db-filedb/src/FileDb2.ts, jovo-integrations/jovo-db-firestore/src/Firestore.ts, jovo-integrations/jovo-db-mongodb/src/MongoDb.ts, jovo-integrations/jovo-db-mysql/src/MySQL.ts
Adds `updatedAt` property to db integrations. Currently not supported on `MySQL` as it would break existing tables.
=> ✨ Adds updatedAt to databases

jovo-integrations/jovo-platform-dialogflow/src/core/DialogflowResponse.ts
https://github.com/jovotech/jovo-framework/issues/462
- [ x] My code follows the code style of this project
=> attempt to fix #462 

jovo-integrations/jovo-platform-dialogflow/package.json, jovo-integrations/jovo-platform-dialogflow/sample-response-json/v2/ASK.json, jovo-integrations/jovo-platform-dialogflow/sample-response-json/v2/TELL.json, jovo-integrations/jovo-platform-dialogflow/test/DialogflowResponse.test.ts, jovo-integrations/jovo-platform-dialogflow/test/dummy.test.ts
Add tests for `hasState` and `hasSessionData` fixes in #464 
- [ x] I have added tests to cover my changes
=> Add tests for `hasState` and `hasSessionData` 

docs/basic-concepts/requests-responses/response.md, jovo-integrations/jovo-platform-googleassistant/src/core/GoogleActionResponse.ts
Documentation was not updated for #479 
- [ x] I have updated the documentation accordingly
=> Add google res getters

docs/basic-concepts/requests-responses/response.md, jovo-integrations/jovo-platform-googleassistant/sample-response-json/v2/ASK.json, jovo-integrations/jovo-platform-googleassistant/src/core/GoogleActionResponse.ts, jovo-integrations/jovo-platform-googleassistant/test/GoogleActionResponse.test.ts
Adding the following Google Action response getters:
`getCard()`
`hasBasicCard()`
`hasImageCard()`
`hasMediaResponse()`
`getMediaResponse()`
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My change requires a change to the documentation
- [x ] I have added tests to cover my changes
=> Add Google Action Response getters

jovo-framework/package.json, jovo-integrations/jovo-cms-airtable/package.json, jovo-integrations/jovo-cms-googlesheets/package.json, jovo-integrations/jovo-db-datastore/package.json, jovo-integrations/jovo-db-dynamodb/package.json, jovo-integrations/jovo-db-filedb/package.json, jovo-integrations/jovo-db-mongodb/package.json, jovo-integrations/jovo-platform-dialogflow/package.json, jovo-integrations/jovo-platform-googleassistant/package.json
These dependencies are required by code in various packages, but were missing from package.json files.  These were necessary to get the unit tests to pass without hoisting dependencies.  When dependencies are hoisted, these problems are hidden: as long as some package in the repo lists these dependencies, they are made available to all packages.
- [ x] My code follows the code style of this project
=> Add missing dependencies

jovo-core/src/Conversation.ts, jovo-core/src/TestHost.ts
Added Conversation.sendToApp method to pass JovoRequest directly to app.handle
Added new TestHost class to jovo-core that simply holds request, response and error objects.
https://community.jovo.tech/t/feature-proposal-same-process-testing/336
https://community.jovo.tech/t/unit-testing-mocking-api-calls/342
#469
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project
- [ x] My change requires a change to the documentation
=> Send test requests directly to app object

README.md
=> :memo: Add transactions to Google Assistant features

docs/README.md
=> :memo: Fix links in README

jovo-integrations/jovo-platform-alexa/src/core/AlexaResponse.ts, jovo-integrations/jovo-platform-alexa/test/AlexaResponse.test.ts
Address an issue using `getReprompt` on an alexa tell response that would generate an error rather than return `undefined`. 
- [X ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have added tests to cover my changes
=> Address getRepropmt issue for Alexa

jovo-integrations/jovo-plugin-debugger/src/JovoDebugger.ts
Use correct intent name in debugger.
https://github.com/jovotech/jovo-framework/issues/495
=> Fix AUDIOPLAYER.AlexaSkill.PlaybackFinished intent name in debugger.

README.md
=> add "step by step contributing"-link to README.md

docs/basic-concepts/requests-responses/response.md
add info about using `getPlatformResponse()` for Google Assistant response getters.
- [x ] New feature (non-breaking change which adds functionality)
=> Update Google Assistant response getter documentation

docs/basic-concepts/requests-responses/request.md, jovo-platforms/jovo-platform-alexa/sample-request-json/v1/AutomotiveLaunchRequest.json, jovo-platforms/jovo-platform-alexa/src/core/AlexaRequest.ts, jovo-platforms/jovo-platform-alexa/test/AlexaRequest.test.ts
add `hasAutomotive` getter for Alexa
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My change requires a change to the documentation
- [x ] I have added tests to cover my changes
- [ x] All new and existing tests passed
=> #505 add hasAutomotive getter

docs/basic-concepts/output/object.md
I've suggested this as I found it useful to see the proper readable output in AWS CloudWatch while debugging my app. Before this I was just seeing [object Object] in the console and realised it needed to be converted to a JSON string first.
=> Update to this.$output - console.log 

docs/basic-concepts/output/object.md
Left unnecessary brackets in last PR, my apologies!
=> Removed unnecessary brackets

jovo-core/src/Extensible.ts, jovo-core/src/Interfaces.ts, jovo-platforms/jovo-platform-googleassistant/package-lock.json, package-lock.json
=> Refactored loading of the config-data.

jovo-integrations/jovo-cms-airtable/test/AirtableCMS.test.ts, jovo-integrations/jovo-cms-airtable/test/DefaultTable.test.ts, jovo-integrations/jovo-cms-airtable/test/ResponsesTable.test.ts, jovo-integrations/jovo-cms-googlesheets/test/DefaultSheet.test.ts, jovo-integrations/jovo-cms-googlesheets/test/GoogleSheetsCMS.test.ts, jovo-integrations/jovo-cms-googlesheets/test/ResponsesSheet.test.ts, jovo-integrations/jovo-db-dynamodb/test/DynamoDb.test.ts, jovo-integrations/jovo-db-filedb/test/FileDb.test.ts, jovo-integrations/jovo-db-filedb/test/FileDb2.test.ts, jovo-integrations/jovo-db-mongodb/test/MongoDb.test.ts
Fixes a bug in the MongoDB tests, where the connection was closed abruptly, which caused a `MongoNetworkError: read ECONNRESET` error. Also sets the `NODE_ENV` of some unit tests to `UNIT_TEST` to fix the `MaxListenersExceededWarning`, which was caused by the initialization of `BaseApp()` objects.
=> ✅ 🐛 Fixes bug where mongodb connection was closed abruptly | ✅ Sets NODE_ENV to UNIT_TEST to fix MaxListenersExceededWarnings

docs/getting-started/README.md
=> Fix a link in README.

README.md, docs/basic-concepts/routing/input.md
=>  📝 Adds input validation to TOC

jovo-integrations/jovo-cms-airtable/src/ResponsesTable.ts, jovo-integrations/jovo-cms-googlesheets/src/ResponsesSheet.ts, jovo-integrations/jovo-cms-googlesheets/test/ResponsesSheet.test.ts
=>  Fix Bug with multiple Response Sheets not extending each other

jovo-integrations/jovo-plugin-pulselabs/.npmignore, jovo-integrations/jovo-plugin-pulselabs/LICENSE, jovo-integrations/jovo-plugin-pulselabs/README.md, jovo-integrations/jovo-plugin-pulselabs/package.json, jovo-integrations/jovo-plugin-pulselabs/src/PulseLabs.ts, jovo-integrations/jovo-plugin-pulselabs/src/index.js, jovo-integrations/jovo-plugin-pulselabs/src/index.ts, jovo-integrations/jovo-plugin-pulselabs/test/dummy.test.ts, jovo-integrations/jovo-plugin-pulselabs/tsconfig.json, jovo-integrations/jovo-plugin-pulselabs/tslint.json
=> :sparkles: Add Pulse Labs Plugin

jovo-platforms/jovo-platform-dialogflow/src/index.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/Twilio/Twilio.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/Twilio/TwilioUser.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/Twilio/interfaces.ts
Adds support for Twilio Dialogflow integration. Mainly just utility methods for parsing the Twilio information sent to dialogflow in the originalDetectIntentRequest payload.
=> Twilio Dialogflow Integration

jovo-framework/src/middleware/Component.ts
🏷 sets ComponentResponse.data as optional property. Depending on the response's status the data property might be undefined (REJECTED & ERROR)
🏷 Adds error? property to ComponentResponse. The component should be able to parse the error as well instead of just returning a response with the status set to ERROR
=> Components: updates response interface

jovo-framework/package.json, jovo-framework/src/middleware/logging/BasicLogging.ts, package-lock.json
By setting `excludedResponseObjects` & `excludedRequestObjects` parts of the log can be excluded.
The values of those parameters are supposed to be object-property-paths just like for `requestObjects` and `responseObjects`.
Additionally, the value can be replaced by setting `excludeReplaceValue` to something else than `undefined`.
=> Added possibility to partially exclude and replace the log.

jovo-platforms/jovo-platform-googleassistant/src/core/GoogleActionRequest.ts
hasScreenInterface did watch for audio cap
=> :bug: hasScreenInterface did watch for audio cap

docs/configuration/hosting/README.md, docs/configuration/hosting/http-host.md, jovo-framework/src/hosts/HttpHost.ts
Example showing how to host a jovo app using nodejs built-in http server.
I did not fully update the documentation since I think this feature is very niche and users will preferably use Express when they can. Still, nice tool to have.
=> :sparkles: Hosting using nodejs built-in http server

docs/getting-started/README.md
Fixed 2 small typos in one of the README files.
- [ x] Bug fix (non-breaking change which fixes an issue)
None of the following items are relevant to the submitted change.
=> Fixed typos in readme

jovo-framework/src/middleware/user/JovoUser.ts, jovo-integrations/jovo-platform-alexa/src/core/AlexaRequest.ts
slot value isn't correct when  Dynamic Entities are use.
We should parse resolutionsPerAuthority to find the correct id.
=> fix slot resolutions for Dynamic Entities

docs/configuration/README.md
=> Update the config file

docs/basic-concepts/requests-responses/response.md, docs/configuration/project-js.md
=> Chrisjoj patch 3

docs/advanced-concepts/hooks.md, docs/basic-concepts/requests-responses/README.md, docs/basic-concepts/requests-responses/response.md, docs/configuration/project-js.md, docs/getting-started/installation/README.md, docs/integrations/analytics/botanalytics.md, docs/integrations/cms/airtable.md, docs/integrations/cms/google-sheets.md, docs/platforms/amazon-alexa/data.md, docs/platforms/amazon-alexa/dialog.md, docs/platforms/amazon-alexa/in-skill-purchases.md, docs/platforms/amazon-alexa/pay.md, docs/platforms/amazon-alexa/visual.md, docs/platforms/google-assistant/daily-update.md, docs/platforms/google-assistant/media-response.md, docs/platforms/google-assistant/routine-suggestion.md, docs/platforms/google-assistant/transactions.md
Trying to get started with Jovo and noticed a few minor errors in the documentation. 
Fixes:
- Spelling
- Typos
- Missing words
=> :pencil2: Minor changes to docs

docs/platforms/google-assistant/visual.md
Fixed example links inside documentation for both Javascript and Typescript examples about Google Assistant visual-output
=> :pencil: Fixed example links inside documentation for both Javascript and Typescript examples about Google Assistant visual-output

examples/javascript/databases/src/app.js, jovo-integrations/jovo-db-datastore/package-lock.json, jovo-integrations/jovo-db-datastore/package.json, jovo-integrations/jovo-db-datastore/src/DatastoreDb.ts, jovo-integrations/jovo-db-datastore/test/DatastoreDb.test.ts, package-lock.json, package.json
Updates `@google-cloud/datastore` package to version 3.^ to fix security issue.
=> ⬆️ updates @google-cloud/datastore to v3^

jovo-platforms/jovo-platform-alexa/src/core/AlexaRequest.ts, jovo-platforms/jovo-platform-alexa/src/core/AlexaResponse.ts, jovo-platforms/jovo-platform-alexa/src/core/AlexaSkill.ts, jovo-platforms/jovo-platform-alexa/src/modules/AplPlugin.ts
add hasAPLTInterface ti support new echo dot.
https://developer.amazon.com/fr/docs/alexa-presentation-language/aplt-interface.html
=> add hasAPLTInterface for character displays devices

jovo-framework/src/index.ts, jovo-framework/src/middleware/user/JovoUser.ts
This is useful for platforms that do not provide session-storage functionalitites.
Session-data can now be saved in the user-database, thus platforms which do not provide session-storage functionalities can use this session-data instead.
=> ✨ session-data can be saved in the database

docs/workflows/cli/build.md, docs/workflows/cli/convert.md, docs/workflows/cli/deploy.md, docs/workflows/cli/get.md, docs/workflows/cli/load.md, docs/workflows/cli/new.md, docs/workflows/cli/run.md
=> :memo: Fix images on workflow docs

docs/advanced-concepts/components/README.md, docs/advanced-concepts/components/developing-components.md, docs/advanced-concepts/components/using-components.md
=> 📝 updates code examples and fixes dead links in component docs

jovo-core/package-lock.json, jovo-framework/package-lock.json, jovo-integrations/jovo-analytics-bespoken/package-lock.json, jovo-integrations/jovo-analytics-botanalytics/package-lock.json, jovo-integrations/jovo-analytics-chatbase/package-lock.json, jovo-integrations/jovo-analytics-dashbot/package-lock.json, jovo-integrations/jovo-analytics-voicehero/package-lock.json, jovo-integrations/jovo-cms-airtable/package-lock.json, jovo-integrations/jovo-cms-googlesheets/package-lock.json, jovo-integrations/jovo-cms-i18next/package-lock.json, jovo-integrations/jovo-db-cosmosdb/package-lock.json, jovo-integrations/jovo-db-datastore/package-lock.json, jovo-integrations/jovo-db-dynamodb/package-lock.json, jovo-integrations/jovo-db-firestore/package-lock.json, jovo-integrations/jovo-db-mongodb/package-lock.json, jovo-integrations/jovo-db-mysql/package-lock.json, jovo-integrations/jovo-nlu-dialogflow/package-lock.json, jovo-integrations/jovo-plugin-debugger/package-lock.json, jovo-integrations/jovo-plugin-lmtester/package-lock.json, jovo-integrations/jovo-plugin-pulselabs/package-lock.json, jovo-platforms/jovo-platform-alexa/package-lock.json, jovo-platforms/jovo-platform-facebookmessenger/src/FacebookMessenger.ts, jovo-platforms/jovo-platform-facebookmessenger/src/core/MessengerBot.ts, jovo-platforms/jovo-platform-facebookmessenger/src/core/MessengerBotRequest.ts, jovo-platforms/jovo-platform-facebookmessenger/src/index.ts, jovo-platforms/jovo-platform-facebookmessenger/src/modules/FacebookMessengerCore.ts, jovo-platforms/jovo-platform-facebookmessenger/test/FrameworkBase.test.ts, jovo-platforms/jovo-platform-googleassistant/package-lock.json, package-lock.json
- Added missing initialization of Speechbuilders & platform-specific Jovo-instance.
- Implemented getLocale-method that there are no problems with I18N, at this point only a single locale for a facebook-messenger-bot is supported.
=> 🐛 Fixed bugs of jovo-platform-facebookmessenger

jovo-core/src/Extensible.ts, jovo-framework/src/middleware/Handler.ts, jovo-framework/test/config.test.ts, jovo-integrations/jovo-analytics-googleanalytics/package.json, jovo-integrations/jovo-nlu-dialogflow/package.json, jovo-integrations/jovo-nlu-dialogflow/src/DialogflowNlu.ts, jovo-platforms/jovo-platform-alexa/src/Alexa.ts, jovo-platforms/jovo-platform-alexa/test/FrameworkBase.test.ts, jovo-platforms/jovo-platform-facebookmessenger/package.json, jovo-platforms/jovo-platform-facebookmessenger/src/FacebookMessenger.ts, jovo-platforms/jovo-platform-facebookmessenger/test/FrameworkBase.test.ts, jovo-platforms/jovo-platform-googleassistant/src/GoogleAssistant.ts, jovo-platforms/jovo-platform-googleassistant/test/FrameworkBase.test.ts, jovo-platforms/jovo-platform-sapcai/src/SapCai.ts, jovo-platforms/jovo-platform-sapcai/test/FrameworkBase.test.ts
- Fixed bug that was a follow-up bug of the config-changes
- DialogflowNlu & FacebookMessenger use `$config` of `Jovo`. That way it can be augmented at runtime.
=> 🎨 Improved code, DialogflowNlu & FacebookMessenger now use the request-config

jovo-integrations/jovo-nlu-dialogflow/src/DialogflowNlu.ts
Fixed bug that would override request-config and corrected config-paths
=> 🐛 DialogflowNlu: Fixed bug that would cause request-config to be overridden

jovo-framework/src/middleware/Handler.ts
The `Handler` now also uses the request-config in `jovo.$config`.
=> ✨ Handler uses the request-config in favor of the app-config

jovo-platforms/jovo-platform-alexa/src/core/AlexaSkill.ts
The getUserId() function pulled the data from the request instead of calling the $user.getId() method.
Issue #630
=> fixes alexaSkill.getUserId() bug

README.md
Fix getting started link on README.
=> Fix get started link on README

docs/platforms/amazon-alexa/README.md, docs/platforms/google-assistant/README.md, jovo-platforms/jovo-platform-alexa/src/core/AlexaRequest.ts, jovo-platforms/jovo-platform-alexa/src/core/AlexaSpeechBuilder.ts, jovo-platforms/jovo-platform-alexa/src/core/AlexaUser.ts, jovo-platforms/jovo-platform-alexa/src/core/Interfaces.ts, jovo-platforms/jovo-platform-alexa/src/index.ts, jovo-platforms/jovo-platform-alexa/src/modules/DialogInterface.ts, jovo-platforms/jovo-platform-dialogflow/package-lock.json, jovo-platforms/jovo-platform-dialogflow/src/core/DialogflowRequest.ts, jovo-platforms/jovo-platform-dialogflow/src/core/DialogflowResponse.ts, jovo-platforms/jovo-platform-dialogflow/src/core/Interfaces.ts, jovo-platforms/jovo-platform-dialogflow/src/index.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/DialogflowPlugin.ts, jovo-platforms/jovo-platform-googleassistant/package-lock.json, jovo-platforms/jovo-platform-googleassistant/package.json, jovo-platforms/jovo-platform-googleassistant/src/core/Interfaces.ts, jovo-platforms/jovo-platform-googleassistant/src/index.ts, jovo-platforms/jovo-platform-googleassistant/src/modules/GoogleAssistantCore.ts
- Adjusted Dynamic Entity Functions
- Alexa Emotions
- Voice Profiles
- Support for Session Entities
=> ✨ Alexa & GoogleAssistant Feature Parity

docs/integrations/databases/mongodb.md
=> 🎨 Enhance MongoDb Docs with Troubleshooting Section

docs/platforms/google-assistant/visual.md
Fixes errors in documentation for [Google Assistant - Visual Output](https://www.jovo.tech/docs/google-assistant/visual-output).
Closes https://github.com/jovotech/jovo-framework/issues/657
=> 📝 Fix docs for Google Assistant Visual Output

docs/nav.json
=> Adds HTTP Post docs page to nav.json

jovo-platforms/jovo-platform-googleassistant/src/index.ts, jovo-platforms/jovo-platform-googleassistant/src/modules/Cards.ts, jovo-platforms/jovo-platform-googleassistant/src/response/Table.ts, jovo-platforms/jovo-platform-googleassistant/test/Cards.test.ts
Fix malformed response for Google Assistant Table Cards.
Closes https://github.com/jovotech/jovo-framework/issues/660
=> 🐛 Fix malformed response for Google Assistant Table Cards

docs/getting-started/installation/README.md, docs/getting-started/installation/upgrading.md, docs/getting-started/installation/v2-migration.md
=> :memo: Update upgrading guides

docs/integrations/nlu/dialogflow-nlu.md, docs/integrations/slu/lex-slu.md, docs/integrations/tts/polly-tts.md
=> 📝 Corrected docs

docs/integrations/asr/README.md, docs/integrations/asr/azure-asr.md, docs/integrations/asr/gcloud-asr.md, docs/integrations/nlu/README.md, docs/integrations/nlu/dialogflow-nlu.md, docs/nav.json
=> 🐛 Update integration routes

jovo-integrations/jovo-slu-witai/src/WitAiSlu.ts
=> 🐛 Fixed WitAiSlu bug

docs/advanced-concepts/components/README.md, docs/advanced-concepts/components/developing-components.md, docs/advanced-concepts/components/using-components.md
=> updates component docs to v3

docs/platforms/core-platform/README.md, docs/platforms/facebook-messenger/README.md
=> 📝 Removed backslashes from docs

jovo-core/src/core/Extensible.ts
The config is now correctly set.  Objects will no longer overwrite other objects. They are merged instead.
=> 🐛 Fixed invalid config-handling

docs/platforms/core-platform/README.md, examples/javascript/06_core/hello-world/src/app.js, examples/typescript/06_core/hello-world/src/app.ts, jovo-platforms/jovo-platform-core/src/core/CorePlatformApp.ts
Implemented `showQuickReplies`
=> ✨ Implemented showQuickReplies

docs/platforms/samsung-bixby/audioplayer.md, jovo-platforms/jovo-platform-bixby/src/modules/BixbyAudioPlayer.ts
Fixes a bug, which kept the Bixby AudioPlayer from enqueuing audio streams.
=> 👌 Adjust Bixby AudioPlayer Functionality

jovo-platforms/jovo-platform-twilioautopilot/src/core/AutopilotResponse.ts, jovo-platforms/jovo-platform-twilioautopilot/src/modules/AutopilotCore.ts, jovo-platforms/jovo-platform-twilioautopilot/test/FrameworkBase.test.ts
* always converts the output to SSML now (makes it consistent across platforms)
* fixes: AutopilotResponse.fromJSON() -> created object without parsing the JSON
* fixes: AutopilotResponse.isAsk() & isTell() -> these were WIP implementations that I forgot to finish before release
* removes some unused imports
* tests: always resets the local FileDb file before running the tests. Caused errors from time to time because of malformed JSON files.
=> Autopilot: fixes AutopilotResponse.fromJSON(), isAsk(), isTell() | converts output to SSML and general clean up

docs/platforms/samsung-bixby/README.md, docs/platforms/samsung-bixby/audioplayer.md
=> 📝 Adjust Bixby Docs to new Templates

docs/tools/cli/run.md
=> 📝 Adjust Docs for --inspect Flag

docs/getting-started/installation/README.md
=> 📝 Updating documentation

jovo-platforms/jovo-platform-twilioautopilot/src/core/AutopilotBot.ts, jovo-platforms/jovo-platform-twilioautopilot/src/core/AutopilotRequest.ts
Adds the missing `getRawText()` implementation. Also adds getters/setters for the following request properties: `CurrentTaskConfidence` and `NextBestTask`
=> Autopilot: bug fixes and new helper methods

jovo-core/src/core/Platform.ts, jovo-platforms/jovo-platform-alexa/src/Alexa.ts, jovo-platforms/jovo-platform-bixby/src/Bixby.ts, jovo-platforms/jovo-platform-core/src/CorePlatform.ts, jovo-platforms/jovo-platform-dialogflow/src/Dialogflow.ts, jovo-platforms/jovo-platform-googleassistant/src/GoogleAssistant.ts, jovo-platforms/jovo-platform-sapcai/src/SapCai.ts, jovo-platforms/jovo-platform-twilioautopilot/src/Autopilot.ts
Added missing setup-middleware calls for all platforms.
Implemented a default setup-function in `Platform` as well.
=> 🐛 Added missing setup-middleware calls

jovo-integrations/jovo-nlu-nlpjs/package.json, jovo-integrations/jovo-nlu-nlpjs/src/NlpjsNlu.ts
- Fixed a type-bug
- Added possibility to prepare the model via callback that can be passed to the config
=> ✨ NlpjsNlu - Implemented possibility to prepare model via callback

jovo-core/src/plugins/Handler.ts
Added an extra conditional check to handle the case, when handler returns `null`, as described in issue (https://github.com/jovotech/jovo-framework/issues/700).
=> 🐛 Added additional condition to check if handler return type is null

docs/platforms/google-assistant/transactions.md
The official documentation changed recently. This PR updates those locations in the docs.
* Update links
=> Update Google Assistant digital transactions links

jovo-platforms/jovo-platform-googleassistant/src/core/GoogleAction.ts
Corrected logic for retrieving project-ids in staged environments
=> 🐛 Corrected logic for retrieving project-ids in staged environments

jovo-platforms/jovo-platform-facebookmessenger/src/FacebookMessenger.ts, jovo-platforms/jovo-platform-facebookmessenger/src/core/MessengerBot.ts, jovo-platforms/jovo-platform-facebookmessenger/src/index.ts, jovo-platforms/jovo-platform-facebookmessenger/src/modules/FacebookMessengerCore.ts
Fixed forgotten statement
Satisfied linter issue
=> 🐛🚨 [FacebookMessenger] Fixed bug & satisfied linter

docs/platforms/amazon-alexa/skillevents.md
Replaced this.getUserId() (deprecated) and this.$user.Id() (never worked) with this.$user.getId().
=> Replaced wrong and deprecated methods

jovo-platforms/jovo-platform-twilioautopilot/src/core/AutopilotRequestBuilder.ts, jovo-platforms/jovo-platform-twilioautopilot/test/FrameworkBase.test.ts
using FileDb with a static user ID for each of the requests resulted in a corrupt db.json file. Made the tests fail sometimes. To fix that we switched to FileDb2, i.e. each user has their own file, and changed the RequestBuilder to add a random user ID to each request by default. Because of that we also deleted the randomUserId stuff from the test files.
=> Autopilot: fixes tests

jovo-platforms/jovo-platform-twilioautopilot/test/FrameworkBase.test.ts
=> Autopilot: adds delay to clearing db folder after tests

jovo-integrations/jovo-analytics-chatbase/README.md
=> Chatbase: used wrong property name for version in docs

jovo-integrations/jovo-analytics-chatbase/src/ChatbaseGoogleAssistant.ts, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/Cancel.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/CompletePurchase.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/DefaultWelcomeIntent.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/HealthCheck.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/HelpIntent.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/MediaFinished.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/OnPermissionName.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/OnPermissionNotification.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/OnPermissionPreciseLocation.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/OnPlace.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/RegisterUpdateCancelled.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/RegisterUpdateOk.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/SignInCancelled.json, jovo-platforms/jovo-platform-dialogflow/sample-request-json/v2/google/SignInOk.json, jovo-platforms/jovo-platform-googleassistant/test/basics.test.ts
=> Chatbase: used wrong helper to access google user id

examples/javascript/08_lindenbaum/hello-world/src/app.js, examples/typescript/08_lindenbaum/hello-world/models/de-DE.json, examples/typescript/08_lindenbaum/hello-world/src/app.ts
=> Lindenbaum: adds de-DE files to examples

jovo-integrations/jovo-analytics-chatbase/src/ChatbaseAlexa.ts
fixes https://github.com/jovotech/jovo-framework/issues/740#issuecomment-627792351
=> Chatbase: fixes error when speech was undefined

jovo-platforms/jovo-platform-alexa/docs/in-skill-purchases.md
=> fixed handling of refunding an item user does not own

jovo-framework/src/middleware/user/JovoUser.ts, jovo-integrations/jovo-db-datastore/src/DatastoreDb.ts, jovo-integrations/jovo-db-dynamodb/src/DynamoDb.ts, jovo-integrations/jovo-db-filedb/src/FileDb.ts, jovo-integrations/jovo-db-filedb/src/FileDb2.ts, jovo-integrations/jovo-db-firestore/src/Firestore.ts, jovo-integrations/jovo-db-mongodb/src/MongoDb.ts, jovo-integrations/jovo-db-mysql/src/MySQL.ts
=> :recycle: Update load, save, delete parameters

jovo-core/src/enums.ts, jovo-platforms/jovo-platform-lindenbaum/README.md, jovo-platforms/jovo-platform-lindenbaum/src/ExpressJsMiddleware.ts, jovo-platforms/jovo-platform-lindenbaum/src/core/LindenbaumRequest.ts, jovo-platforms/jovo-platform-lindenbaum/src/modules/LindenbaumCore.ts
Adds support for the `/inactivity` endpoint.
https://app.swaggerhub.com/apis/Lindenbaum-GmbH/CVP-Bot-API/1.0.13#/bot/inactivity
=> Lindenbaum: adds support for the /inactivity endpoint

jovo-integrations/jovo-db-platformstorage/src/PlatformStorage.ts
Fixed PlatformStorage that used the old core-platform request and response format
=> 🐛 Fixed PlatformStorage bug

jovo-integrations/jovo-plugin-pulselabs/src/PulseLabs.ts
Just checked from which platform the request is coming. If Google Action then used different method according to Pulselabs [documentation](https://dashboard.pulselabs.ai/client/documentation/google/nodejs-webhook)
=> used logGoogleData for Google Action

docs/workflows/unit-testing.md
✏️ Fix unit-testing doc: Link to code example was wrong.
=> :pencil: Update Doc link to unit-testing samples projects

jovo-clients/jovo-client-web/src/components/input/AudioRecorder.ts, jovo-clients/jovo-client-web/src/index.ts, jovo-clients/jovo-client-web/src/util/OSHelper.ts
=> 🐛 Added fix for windows bug that would cause first second to be omitted

jovo-platforms/jovo-platform-facebookmessenger/src/core/MessengerBotUser.ts
Use request config instead of app-config.
=> 🐛 [FB-Messenger] Fixed bug that wrong config would be used

jovo-platforms/jovo-platform-facebookmessenger/src/core/MessengerBotUser.ts
The application will not exit if the profile-loading fails for whatever reason.
Additionally, the error message is clearer.
=> 🐛 Improved profile-loading

docs/basic-concepts/model/README.md
=> Fix link to documentation for automated expansion

jovo-platforms/jovo-platform-alexa/docs/permissions-data.md
=> Events Endpoint is no longer limited to Lambda

docs/workflows/unit-testing.md, jovo-integrations/jovo-plugin-debugger/README.md, jovo-platforms/jovo-platform-alexa/docs/permissions-data.md
=> Update to Docs

jovo-core/package.json, jovo-core/src/util/SpeechBuilder.ts, jovo-platforms/jovo-platform-alexa/src/core/AlexaSpeechBuilder.ts, jovo-platforms/jovo-platform-googleassistant/package.json, jovo-platforms/jovo-platform-googleassistant/src/core/GoogleActionSpeechBuilder.ts, package-lock.json
=> :bug: Unexpected .addAudio() behaviour

jovo-integrations/jovo-asr-azure/README.md, jovo-integrations/jovo-asr-azure/src/AzureAsr.ts, jovo-integrations/jovo-asr-gcloud/README.md, jovo-integrations/jovo-asr-gcloud/src/GCloudAsr.ts, jovo-integrations/jovo-nlu-dialogflow/README.md, jovo-integrations/jovo-nlu-dialogflow/src/DialogflowNlu.ts, jovo-integrations/jovo-nlu-luis/README.md, jovo-integrations/jovo-nlu-luis/src/LuisNlu.ts, jovo-integrations/jovo-nlu-nlpjs/src/NlpjsNlu.ts, jovo-integrations/jovo-nlu-rasa/src/RasaNlu.ts, jovo-integrations/jovo-slu-lex/README.md, jovo-integrations/jovo-slu-lex/src/LexSlu.ts, jovo-integrations/jovo-slu-witai/README.md, jovo-integrations/jovo-slu-witai/src/WitAiSlu.ts, jovo-integrations/jovo-tts-azure/README.md, jovo-integrations/jovo-tts-azure/src/AzureTts.ts, jovo-integrations/jovo-tts-gcloud/README.md, jovo-integrations/jovo-tts-gcloud/src/GCloudTts.ts, jovo-integrations/jovo-tts-polly/README.md, jovo-integrations/jovo-tts-polly/src/PollyTts.ts
Normalizes configuration-handling of ASR-, NLU-, SLU- and TTS-integrations.
Also improves error messages for those integrations.
=> ♻️ Normalize configuration-handling & error-messages of ASR-, NLU-, SLU- and TTS-integrations

examples/typescript/09_googlebusiness/hello-world/models/en-US.json, examples/typescript/09_googlebusiness/hello-world/package.json, examples/typescript/09_googlebusiness/hello-world/src/app.ts, examples/typescript/09_googlebusiness/hello-world/src/config.ts, examples/typescript/09_googlebusiness/hello-world/src/index.ts, examples/typescript/09_googlebusiness/hello-world/test/example.test.ts, examples/typescript/09_googlebusiness/hello-world/tsconfig.json, examples/typescript/09_googlebusiness/hello-world/tslint.json, jovo-platforms/jovo-platform-google-business-messages/README.md, jovo-platforms/jovo-platform-google-business-messages/src/GoogleBusiness.ts, jovo-platforms/jovo-platform-google-business-messages/src/Interfaces.ts, jovo-platforms/jovo-platform-google-business-messages/src/index.ts, jovo-platforms/jovo-platform-google-business-messages/src/modules/Cards.ts
=> Google business docs

jovo-integrations/jovo-nlu-dialogflow/src/DialogflowNlu.ts
The session-id that was passed before was random. 
Now the session-id can be either set via a callback-function in the config or it will fall back to the request's session-id or user-id.
Also improved the error handling to check if the session-id is valid.
=> ♻️ Improve DialogflowNlu session-id for detectIntent-requests

jovo-integrations/jovo-nlu-nlpjs/package.json
=> ⬆️ Upgrade dependencies of jovo-nlu-nlpjs

jovo-integrations/jovo-nlu-nlpjs/src/index.ts
Corrects typed config for NlpjsNlu.
=> 🏷️ Correct NlpjsNlu config typings

jovo-integrations/jovo-asr-azure/src/AzureAsr.ts
The url for speech-recognition has changed. Adjusted request-url.
=> 🐛 Fix changed AzureAsr url

jovo-integrations/jovo-slu-lex/src/LexSlu.ts, jovo-integrations/jovo-slu-witai/src/WitAiSlu.ts
ASR and NLU can be disabled for SLU-integrations. This way they can be used together in conjunction with other ASR/NLU-integrations.
=> ✨ Implement partial usage of SLU-integrations

jovo-integrations/jovo-slu-lex/src/LexSlu.ts, jovo-integrations/jovo-tts-polly/src/PollyTts.ts
Fix bug that would cause the values of the config file to not be considered for validation.
The validation now takes part when the plugin is being installed.
=> 🐛 Fix bug 

jovo-clients/jovo-client-web-vue/README.md, jovo-clients/jovo-client-web-vue/package.json
Moving Vue to the `peerDependencies` will reduce the package size a lot.
=> 🔧 Move Vue to peerDependencies

jovo-core/src/util/SpeechBuilder.ts, jovo-platforms/jovo-platform-dialogflow/src/DialogflowAgent.ts, jovo-platforms/jovo-platform-dialogflow/src/core/DialogflowResponse.ts, jovo-platforms/jovo-platform-dialogflow/src/index.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/DialogflowPhoneGateway/DialogflowPhoneGateway.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/DialogflowPhoneGateway/DialogflowPhoneGatewayUser.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/DialogflowPlugin.ts
Adds new Dialogflow integration for Dialogflow Phone Gateway.  Handles SSML output, which requires a different structure in the response. Adds end_interaction boolean to the response.  When set to true, the phone call will be disconnected.
=> :sparkles: Add Dialogflow Phone Gateway integration

jovo-framework/package.json, jovo-framework/src/middleware/logging/BasicLogging.ts, package-lock.json
Request/Response JSON output is pretty boring. This PR uses `json-colorizer` and `chalk` to make it more colorful and therefore clearer.
It's enabled by default. 
Can be disabled in the config.ts/config.js
```
logging: {
styling: false,
},
```
=> :sparkles: Make fancy JSON output  

jovo-core/src/Interfaces.ts, jovo-framework/src/index.ts, jovo-framework/src/middleware/user/JovoUser.ts
Add `UserData` type for the user-data that it's type can be augmented.
Related issue: #825
=> 🏷️ Add type for user-data

docs/configuration/project-js.md, jovo-platforms/jovo-platform-alexa/README.md, jovo-platforms/jovo-platform-googleassistantconv/README.md
=> 📝 Update docs for platform configuration

jovo-platforms/jovo-platform-dialogflow/package-lock.json, jovo-platforms/jovo-platform-dialogflow/package.json, jovo-platforms/jovo-platform-dialogflow/src/DialogflowAgent.ts, jovo-platforms/jovo-platform-dialogflow/src/index.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/Genesys/Genesys.ts, jovo-platforms/jovo-platform-dialogflow/src/integrations/Genesys/GenesysUser.ts
Dialogflow and Genesys telecommunications provider have a (beta) integration in place:
https://cloud.google.com/dialogflow/es/docs/integrations/genesys
https://help.mypurecloud.com/articles/google-dialogflow-quick-start-guide/
With this Jovo integration you will be able to use your Jovo application as a fulfillment service for the dialogflow agent.
TODO: Documentation and more features.
=> Genesys integration

jovo-platforms/jovo-platform-web/src/WebPlatform.ts, jovo-platforms/jovo-platform-web/src/index.ts
Add re-export to `jovo-platform-web` to avoid having to access the underlying `jovo-platform-core`-package directly.
=> ✨ Add re-export to jovo-platform-web

jovo-platforms/jovo-platform-web/README.md
Only changes to the documentation
=> Update docs for v3.2 release

jovo-clients/jovo-client-web/README.md
=> Jovo Client Web Docs

docs/tools/webhook.md
=> 📝 Fix `jovo deploy` broken link

jovo-platforms/jovo-platform-alexa/src/modules/AplPlugin.ts, jovo-platforms/jovo-platform-googleassistantconv/src/core/GoogleAction.ts, jovo-platforms/jovo-platform-googleassistantconv/src/core/GoogleAssistantRequestBuilder.ts, jovo-platforms/jovo-platform-googleassistantconv/src/core/Interfaces.ts
* Fixes RequestBuilder
* Fixes wrong platform type
* Fixes types
=> Fixes several Google Conversational Actions issues

jovo-platforms/jovo-platform-alexa/src/modules/AplPlugin.ts
Fixes skipped APL-A directive for "non-APL" devices.
=> :bug: Fix ignored APL-A directive #849

jovo-platforms/jovo-platform-googleassistantconv/src/core/GoogleAssistantRequestBuilder.ts
=> :bug: Fix RequestBuilder

jovo-framework/src/hosts/Lambda.ts, jovo-platforms/jovo-platform-googleassistant/src/core/GoogleActionRequest.ts, jovo-platforms/jovo-platform-googleassistant/test/basics.test.ts, jovo-platforms/jovo-platform-googleassistantconv/src/modules/ConversationalActionsCore.ts, package-lock.json
Fixes:
* Missing header on Lambda with API Gateway (used in getGoogleProfile())
* getUserId (in Google Assistant + DF integration)
* removeState() (set _JOVO_STATE_ explicitly to null to remove states)
=> FIx bugs in Google Assistant Integration

docs/basic-concepts/output/visual-output.md, jovo-core/src/Interfaces.ts, jovo-core/src/core/Jovo.ts, jovo-platforms/jovo-platform-facebookmessenger/src/core/MessengerBot.ts, jovo-platforms/jovo-platform-googleassistant/src/modules/Cards.ts, jovo-platforms/jovo-platform-googleassistantconv/src/modules/ConversationalActionsCore.ts, jovo-platforms/jovo-platform-googlebusiness/src/modules/GoogleBusinessCore.ts, jovo-platforms/jovo-platform-sapcai/src/modules/Cards.ts, jovo-platforms/jovo-platform-sapcai/src/response/QuickReply.ts, package-lock.json
- ✨ Implement `showQuickReplies`-method to show quick-replies for all platforms that are capable of displaying them.
closes #852
=> ✨ Abstract quick replies

docs/basic-concepts/routing/README.md, e2e/test/handler.test.ts, jovo-core/src/plugins/Handler.ts, jovo-core/src/plugins/types.ts, jovo-platforms/jovo-platform-alexa/src/index.ts, jovo-platforms/jovo-platform-bixby/src/index.ts, jovo-platforms/jovo-platform-googleassistant/src/GoogleAssistant.ts, jovo-platforms/jovo-platform-googleassistant/src/index.ts, jovo-platforms/jovo-platform-googleassistantconv/src/GoogleAssistant.ts, jovo-platforms/jovo-platform-googleassistantconv/src/index.ts, jovo-platforms/jovo-platform-sapcai/src/index.ts, package-lock.json
- ✨ `setPlatformHandler(platformName: string, ...handlers: Handler[])` should now be used instead of the platform-specific methods for setting handlers like `setAlexaHandler`.
- 🗑️ Deprecated usage of platform-specific methods for settings handlers.
closes #851
=> ✨ Abstract the initialization of the platform handlers into a single function

examples/javascript/02_googleassistantconv/typeoverride/models/en.json, examples/javascript/02_googleassistantconv/typeoverride/package.json, examples/javascript/02_googleassistantconv/typeoverride/project.js, examples/javascript/02_googleassistantconv/typeoverride/src/app.js, examples/javascript/02_googleassistantconv/typeoverride/src/config.js, examples/javascript/02_googleassistantconv/typeoverride/src/index.js, examples/typescript/02_googleassistantconv/rich/src/app.ts, examples/typescript/02_googleassistantconv/typeoverride/models/en.json, examples/typescript/02_googleassistantconv/typeoverride/package.json, examples/typescript/02_googleassistantconv/typeoverride/project.js, examples/typescript/02_googleassistantconv/typeoverride/src/app.ts, examples/typescript/02_googleassistantconv/typeoverride/src/config.ts, examples/typescript/02_googleassistantconv/typeoverride/src/index.ts, examples/typescript/02_googleassistantconv/typeoverride/test/example.test.ts, examples/typescript/02_googleassistantconv/typeoverride/tsconfig.json, examples/typescript/02_googleassistantconv/typeoverride/tslint.json, jovo-platforms/jovo-platform-googleassistantconv/src/core/ConversationalActionRequest.ts, jovo-platforms/jovo-platform-googleassistantconv/src/core/ConversationalActionResponse.ts, jovo-platforms/jovo-platform-googleassistantconv/src/core/GoogleAction.ts, jovo-platforms/jovo-platform-googleassistantconv/src/core/Interfaces.ts, jovo-platforms/jovo-platform-googleassistantconv/src/index.ts, jovo-platforms/jovo-platform-googleassistantconv/src/modules/ConversationalActionsCore.ts, jovo-platforms/jovo-platform-googleassistantconv/src/visuals/BasicCard.ts, package-lock.json
* Adds missing showBasicCard
* Add missing getDeviceName. closes #867
* Improve setTypeOverrides and add example
=> Add missing and broken Google Conversational Action features

examples/typescript/02_googleassistantconv/rich/src/app.ts, jovo-integrations/jovo-plugin-inbox/.npmignore, jovo-integrations/jovo-plugin-inbox/.prettierrc.js, jovo-integrations/jovo-plugin-inbox/CHANGELOG.md, jovo-integrations/jovo-plugin-inbox/LICENSE, jovo-integrations/jovo-plugin-inbox/README.md, jovo-integrations/jovo-plugin-inbox/package-lock.json, jovo-integrations/jovo-plugin-inbox/package.json, jovo-integrations/jovo-plugin-inbox/src/JovoInbox.ts, jovo-integrations/jovo-plugin-inbox/src/SqlInbox.ts, jovo-integrations/jovo-plugin-inbox/src/entity/InboxLog.ts, jovo-integrations/jovo-plugin-inbox/src/index.ts, jovo-integrations/jovo-plugin-inbox/src/interfaces.ts, jovo-integrations/jovo-plugin-inbox/test/dummy.test.ts, jovo-integrations/jovo-plugin-inbox/tsconfig.json, jovo-integrations/jovo-plugin-inbox/tslint.json, jovo-platforms/jovo-platform-googleassistantconv/src/core/Interfaces.ts, jovo-platforms/jovo-platform-googleassistantconv/src/index.ts, jovo-platforms/jovo-platform-googleassistantconv/src/modules/ConversationalActionsCore.ts
Plugin to save conversation/request/response data into a database.
=> :sparkles: Plugin to save conversation data into a database

jovo-integrations/jovo-plugin-debugger/src/JovoDebugger.ts, jovo-platforms/jovo-platform-googleassistantconv/sample-request-json/EndRequest.json, jovo-platforms/jovo-platform-googleassistantconv/sample-request-json/IntentRequest.json, jovo-platforms/jovo-platform-googleassistantconv/sample-request-json/LAUNCH.json, jovo-platforms/jovo-platform-googleassistantconv/sample-request-json/LAUNCH_NEW_USER.json, jovo-platforms/jovo-platform-googleassistantconv/src/core/ConversationalActionRequest.ts, jovo-platforms/jovo-platform-googleassistantconv/src/core/ConversationalActionResponse.ts
* Adds missing functionality to ConversationActionRequest/ConversationActionResponse classes. 
* Update Jovo Debugger plugin
=> :recycle: Add Conversational Actions functionality to Jovo Debugger

jovo-platforms/jovo-platform-alexa/src/core/AlexaRequest.ts, jovo-platforms/jovo-platform-alexa/src/index.ts, jovo-platforms/jovo-platform-dialogflow/src/index.ts
=> 🏷️ Update + export types

jovo-platforms/jovo-platform-googleassistantconv/README.md, jovo-platforms/jovo-platform-googleassistantconv/docs/concepts/scenes.md, jovo-platforms/jovo-platform-googleassistantconv/docs/interfaces/README.md, jovo-platforms/jovo-platform-googleassistantconv/docs/interfaces/media-response.md, jovo-platforms/jovo-platform-googleassistantconv/docs/interfaces/notifications.md, jovo-platforms/jovo-platform-googleassistantconv/docs/interfaces/transactions.md, jovo-platforms/jovo-platform-googleassistantconv/docs/interfaces/visual-output.md, jovo-platforms/jovo-platform-googleassistantconv/docs/request-response/README.md, jovo-platforms/jovo-platform-googleassistantconv/docs/request-response/request.md, jovo-platforms/jovo-platform-googleassistantconv/docs/request-response/response.md, jovo-platforms/jovo-platform-googleassistantconv/docs/user-data.md
Adjust links in Google Conversational Docs.
=> ✏️ Adjust docs for Conversational Actions

jovo-integrations/jovo-analytics-botanalytics/src/BotanalyticsAlexa.ts, jovo-integrations/jovo-analytics-dashbot/src/DashbotAlexa.ts, jovo-integrations/jovo-analytics-dashbot/src/DashbotDialogflow.ts, jovo-integrations/jovo-analytics-dashbot/src/DashbotGoogleAssistant.ts, jovo-integrations/jovo-analytics-dashbot/src/DashbotUniversal.ts, jovo-integrations/jovo-analytics-voicehero/src/VoiceHeroAlexa.ts
Closes #897
Adds error handling to analytics integrations.
=> Add error handling to analytics integrations

jovo-platforms/jovo-platform-alexa/src/modules/AlexaCore.ts
=> Route Alexa.Presentation.APL.RuntimeError requests to ON_ERROR

jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalytics.ts
Allow users to track multiple Google Optimize experiments at once.
=> feat(GoogleAnalytics): support multiple experiments

jovo-integrations/jovo-analytics-googleanalytics/README.md, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalytics.ts, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsAlexa.ts, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsGoogleAssistant.ts
- prevent errors if metadata not set + update documentation
- add health check filters for conversational action
- track Skillevents as Events not pageviews
https://github.com/jovotech/jovo-framework/issues/894 -> error if metadata not set
https://community.jovo.tech/t/exclude-google-assistant-health-check-from-analytics/1555 -> health checks for conversational actions
=> Google Analytics HealthCheck + Crawler Filter update + Event tracking of skill events

docs/basic-concepts/routing/intents.md
I updated only the docs to fix a broken link to external Alexa docs concerning the standard built-in intents.
=> :memo: Update link to external Alexa docs

framework/boilerplate/app.stage.ts, platforms/platform-alexa/src/cli/hooks/BuildHook.ts, platforms/platform-dialogflow/src/cli/hooks/BuildHook.ts, platforms/platform-googleassistant/src/cli/hooks/BuildHook.ts
=> ♻️ Validate models on build 

package-lock.json, platforms/platform-alexa/package.json, platforms/platform-alexa/src/Alexa.ts, platforms/platform-alexa/src/AlexaRequest.ts, platforms/platform-alexa/src/interfaces.ts
=> ✨ Support generating APL from generic output

framework/src/App.ts, framework/src/BaseComponent.ts, framework/src/ComponentPlugin.ts, framework/src/ComponentTree.ts, framework/src/Extensible.ts, framework/src/HandleRequest.ts, framework/src/Jovo.ts, framework/src/MiddlewareCollection.ts, framework/src/decorators/Component.ts, framework/src/errors/ComponentNotFoundError.ts, framework/src/errors/DuplicateGlobalIntentsError.ts, framework/src/index.ts, framework/src/plugins/HandlerPlugin.ts, framework/src/plugins/RouterPlugin.ts, framework/src/plugins/RoutingExecutor.ts, framework/test/App.test.ts, framework/test/Component.test.ts
Implement a `ComponentTree` which allows managing installed components, this includes adding, removing and executing existing components.
=> ✨♻️ Implement `ComponentTree` for easier component-management

docs/handlers.md, docs/output.md, framework/src/Jovo.ts
Now, synchronous platforms are able to take advantage of multiple `$send`-calls as well.
=> ✨ Implement multiple $send calls for synchronous platforms

framework/src/Jovo.ts, framework/src/JovoProxy.ts, platforms/platform-alexa/src/AlexaSkill.ts, platforms/platform-alexa/src/interfaces.ts, platforms/platform-core/src/CorePlatformApp.ts, platforms/platform-facebookmessenger/src/MessengerBot.ts, platforms/platform-googleassistant/src/GoogleAction.ts, platforms/platform-googlebusiness/src/GoogleBusinessBot.ts
Implement `hasScreenInterface` for `Jovo` and all platform-specific classes that extend `Jovo`.
Compared to v3, all platforms that support display return `true` by default now.
=> ✨ Implement `hasScreenInterface`

framework/src/Jovo.ts, framework/src/JovoProxy.ts, platforms/platform-alexa/src/AlexaSkill.ts, platforms/platform-alexa/src/interfaces.ts, platforms/platform-core/src/CorePlatformApp.ts, platforms/platform-facebookmessenger/src/MessengerBot.ts, platforms/platform-googleassistant/src/GoogleAction.ts, platforms/platform-googlebusiness/src/GoogleBusinessBot.ts
Reverts jovotech/jovo-framework#950
=> ⏪️ Revert "✨ Implement `hasScreenInterface`"

integrations/plugin-debugger/src/JovoDebugger.ts, platforms/platform-alexa/src/AlexaRequest.ts, platforms/platform-core/src/CorePlatformRequest.ts, platforms/platform-googleassistant/src/cli/utils/interfaces.ts, platforms/platform-googlebusiness/src/GoogleBusinessRequest.ts
Fix invalid imports that were caused by automatic imports of the IDE.
=> 🐛  Fix invalid imports

docs/logging.md, framework/src/plugins/BasicLogging.ts
The request log was printed twice. This PR removes the first one.
=> 🐛 Fix duplicate request log

docs/components.md, framework/src/Jovo.ts, framework/src/utilities.ts
- Refactored case where no state-stack-item existed
- Added null-check to `forEachDeep`
- Fixed a typing issue of `$resolve`
=> ♻️ Improve `$component` of `Jovo`

platforms/platform-alexa/README.md, platforms/platform-alexa/src/Alexa.ts, platforms/platform-alexa/src/constants.ts
- Implement carousel selection for Alexa. So far only quick-replies were supported.
- Fix small bug that could occur when arguments were `null` in an APLUserEvent.
=> ✨ Implement carousel selection for Alexa

framework/src/JovoDevice.ts, platforms/platform-alexa/src/AlexaPlatform.ts, platforms/platform-core/src/CorePlatformDevice.ts
- Fix invalid import that wasn't changed when platforms were renamed
- Make `JovoDevice` serializable which is
=> 🐛  Fix invalid import and make `JovoDevice` serializable

jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalytics.ts
I'm running into errors while publishing my skill when `canHandleIntent` is called without user data. The error points to where the user id is hashed, so I'm updating the code to return "UNKNOWN_USER" as the user id if one isn't available to hash.
```
2021-07-20T06:21:56.298-05:00 | Error -----------------------------------------------------------------
-- | --
  | 2021-07-20T06:21:56.298-05:00CopyCode: | Code:
  | 2021-07-20T06:21:56.298-05:00 | ERR_INVALID_ARG_TYPE
  | 2021-07-20T06:21:56.298-05:00 | Message:
  | 2021-07-20T06:21:56.298-05:00 | The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
  | 2021-07-20T06:21:56.298-05:00 | Stack:
  | 2021-07-20T06:21:56.298-05:00 | TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument …
```
=> Fix empty user

docs/ridr-lifecycle.md, framework/src/App.ts, framework/src/HandleRequest.ts, framework/src/Jovo.ts, framework/src/Middleware.ts, framework/src/MiddlewareCollection.ts, framework/src/NluPlugin.ts, framework/src/Platform.ts, framework/src/plugins/BasicLogging.ts, framework/src/plugins/HandlerPlugin.ts, framework/src/plugins/OutputPlugin.ts, framework/src/plugins/RouterPlugin.ts, framework/src/plugins/RoutingExecutor.ts, framework/test/Platform.test.ts, integrations/db-dynamodb/src/DynamoDb.ts, integrations/db-filedb/src/FileDb.ts, integrations/nlu-dialogflow/src/DialogflowNlu.ts, integrations/nlu-nlpjs/src/NlpjsNlu.ts, integrations/nlu-rasa/src/RasaNlu.ts, integrations/plugin-debugger/src/JovoDebugger.ts, platforms/platform-alexa/src/AlexaPlatform.ts, platforms/platform-googleassistant/src/GoogleAssistantPlatform.ts, platforms/platform-googlebusiness/src/GoogleBusinessPlatform.ts
Thir PR finalizes the middleware names for the Jovo v4 beta. You can find the names in the `ridr-lifecycle.md` documentation.
- [] My change requires a change to the documentation
=> Finalize middleware naming

docs/components.md, docs/data.md, docs/databases.md, docs/handlers.md, docs/routing.md, docs/state-stack.md, framework/src/App.ts, framework/src/HandleRequest.ts, framework/src/Jovo.ts, framework/src/JovoSession.ts, framework/src/JovoUser.ts, framework/src/plugins/HandlerPlugin.ts, framework/src/plugins/RoutingExecutor.ts, platforms/platform-googleassistant/docs/scenes.md
Only direct properties of `Jovo` should have a `$`-prefix.
=> 🚚 Only use $ for direct properties of `Jovo`

framework/src/MiddlewareCollection.ts, platforms/platform-core/src/interfaces.ts
When running the functions of a `Middleware`, a promise chain was used. Sadly this did not await promises by itself in said chain and therefore it was removed again.
=> 🐛 Fix bug caused by using a promise chain

framework/src/decorators/Component.ts
The logic to automatically add a global handler for `LAUNCH` and `END` was updated.
=> ♻️🐛 Refactor `@Component`-decorator

integrations/plugin-debugger/README.md, integrations/plugin-debugger/src/JovoDebugger.ts, platforms/platform-core/README.md, platforms/platform-core/src/CorePlatform.ts
Fix platform that is used to send the request in the debugger.
=> 🐛 Fix debugger-bug

docs/handlers.md, framework/src/decorators/Intents.ts, framework/src/decorators/Platforms.ts, framework/src/decorators/Types.ts
These decorators now allow passing a single item as well as multiple items or an array.
=> 🏷️ Improve decorator parameters

platforms/platform-alexa/src/AlexaRequest.ts
Fix a bug that caused the input-type to not use the request-type of the request for Alexa.
=> 🐛 Fix a bug that caused the input-type to not use the request-type of the request

framework/src/BaseComponent.ts, framework/src/Jovo.ts
Remove $ from properties of `JovoComponentInfo`
=> 🎨 Remove $ from properties of `JovoComponentInfo`

docs/device.md, framework/src/JovoDevice.ts, framework/src/JovoRequest.ts, framework/test/utilities/platform.ts, platforms/platform-alexa/src/AlexaDevice.ts, platforms/platform-alexa/src/AlexaRequest.ts, platforms/platform-core/src/CoreDevice.ts, platforms/platform-core/src/CoreRequest.ts, platforms/platform-facebookmessenger/src/FacebookMessengerDevice.ts, platforms/platform-facebookmessenger/src/FacebookMessengerRequest.ts, platforms/platform-googleassistant/src/GoogleAssistantDevice.ts, platforms/platform-googleassistant/src/GoogleAssistantRequest.ts, platforms/platform-googlebusiness/src/GoogleBusinessDevice.ts, platforms/platform-googlebusiness/src/GoogleBusinessRequest.ts
- `JovoRequest` now has an abstract method `getDeviceCapabilities` which will be used by `JovoDevice` to set the capabilities when instantiating the class.
- Implement missing logic to set capabilities for the Core-platform
=> ♻️ Refactor logic to set `capabilities` in classes that extend `JovoDevice`

jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsAlexa.ts, jovo-integrations/jovo-analytics-googleanalytics/src/GoogleAnalyticsInstance.ts
Because Alexa Skill Events are not awaited the lambda will try to finish processing in the next request. This results in an error.
=> :bug: AlexaSkill Event Errors in GoogleAnalytics

docs/README.md
This PR adds a `README.md` file to the `docs` folder.
=> 📝 Add getting started docs

docs/README.md, docs/app-config.md, docs/components.md, docs/data.md, docs/databases.md, docs/device.md, docs/entities.md, docs/handlers.md, docs/input.md, docs/installation.md, docs/jovo-properties.md, docs/logging.md, docs/models.md, docs/nlu.md, docs/output-classes.md, docs/output.md, docs/platforms.md, docs/project-config.md, docs/ridr-lifecycle.md, docs/routing.md, docs/staging.md, docs/state-stack.md, docs/user.md
Front matter is used by the Jovo v4 (WIP) website to display doc pages
=> 📝  Add front matter to docs

docs/hooks.md, framework/src/App.ts, framework/src/MiddlewareCollection.ts
Implement `hook`-method for `App` for easier hooking into middlewares without implementing a plugin.
Also improved middleware suggestions for `middleware`-method of `App`.
=> ✨ Implement hooks

framework/src/App.ts
- App can only be initialized once, afterwards, nothing occurs
- In some edge cases this can be bypassed by setting `initialized` to `false` but this will require casting
=> 👔 Update initialization logic

platforms/platform-googlebusiness/src/GoogleBusinessPlatform.ts, platforms/platform-googlebusiness/src/index.ts
Like described [here](https://developers.google.com/business-communications/business-messages/guides/learn/best-practices#check_for_duplicate_incoming_messages), it is important to check whether the `messageId` was already handled and ignore the request in that case.
=> ✨ Implement handling of potential duplicate messages

package.json, scripts/update-peer-dependencies.js
- Implement a script to update the `@jovotech/framework` peer dependency of all related packages. 
- Connect the script by automatically calling it in `postversion`. [Here](https://github.com/lerna/lerna/tree/main/commands/publish#lifecycle-scripts) is more information.
- The version of the peer dependency is no longer a range but rather strictly the version of the framework package
- When making changes to the framework package and publishing, every other package will be also published, therefore we can assure that the version that is installed is exactly the one that was used for publishing.
=> 🔨 Implement script for updating `@jovotech/framework` peer dependency

platforms/platform-googleassistant/src/cli/hooks/BuildHook.ts
Addresses framework-specific fixes with jovotech/jovo-model/pull/51.
=> 🐛 Add global intents to actions.yml

package.json
Use `version` instead of `postversion` otherwise, changes were omitted.
=> 🔨 Use version hook instead of postversion hook

framework/package.json
Add missing dependency `uuid` to `framework` package.
=> 🐛➕ Add missing dependency

docs/output-classes.md, docs/output.md
This PR is related to https://github.com/jovotech/jovo-v4-template/pull/9
=> 📝 Add OutputTemplate imports

framework/src/testsuite/TestSuite.ts
Since `this.$entities` will be instantiated in the constructor of `Jovo.ts`, we have to set it manually in the TestSuite.
=> :bug: Set entities manually

common/src/JovoError.ts, docs/error-handling.md, framework/src/testsuite/TestSuite.ts, integrations/analytics-dashbot/src/plugins/DashbotAnalyticsPlugin.ts, integrations/nlu-snips/src/SnipsNlu.ts, platforms/platform-alexa/src/api/AlexaApi.ts, platforms/platform-alexa/src/api/CustomerProfileApi.ts, platforms/platform-alexa/src/api/ReminderApi.ts, platforms/platform-facebookmessenger/src/FacebookMessengerPlatform.ts
Remove `details` from JovoError and add `package` property.
=> ♻️ Refactor `JovoError`

framework/src/Extensible.ts, framework/src/Platform.ts, framework/src/Plugin.ts, framework/src/plugins/DbPlugin.ts, framework/src/plugins/NluPlugin.ts, integrations/analytics-dashbot/src/plugins/DashbotAlexa.ts, integrations/analytics-dashbot/src/plugins/DashbotFacebook.ts, integrations/analytics-dashbot/src/plugins/DashbotGoogleAssistant.ts, integrations/nlu-snips/src/SnipsNlu.ts, integrations/plugin-debugger/src/JovoDebugger.ts, platforms/platform-core/src/CorePlatform.ts, platforms/platform-facebookmessenger/src/FacebookMessengerPlatform.ts, platforms/platform-web/.npmignore, platforms/platform-web/CHANGELOG.md, platforms/platform-web/README.md, platforms/platform-web/jest.config.js, platforms/platform-web/package.json, platforms/platform-web/sample-requests/IntentRequest.json, platforms/platform-web/sample-requests/LaunchRequest.json, platforms/platform-web/src/index.ts, platforms/platform-web/test/dummy.test.ts, platforms/platform-web/tsconfig.build.cjs.json, platforms/platform-web/tsconfig.build.esm2015.json, platforms/platform-web/tsconfig.build.esm5.json, platforms/platform-web/tsconfig.build.types.json, platforms/platform-web/tsconfig.json
- Implement WebPlatform based on CorePlatform.
Note: _This PR is based on #1100_
=> ✨ Implement WebPlatform

common/src/index.ts, framework/src/App.ts, integrations/analytics-dashbot/src/plugins/DashbotFacebook.ts, integrations/plugin-debugger/src/JovoDebugger.ts, output/src/OutputTemplateConverter.ts, platforms/platform-alexa/src/interfaces.ts, platforms/platform-dialogflow/src/output/decorators/validation/IsValidRbmSuggestedActionContentObject.ts, platforms/platform-dialogflow/src/output/decorators/validation/IsValidRbmSuggestionContentObject.ts, platforms/platform-googlebusiness/src/output/models/GoogleBusinessOutputTemplateResponse.ts
This PR fixes Linter issues and introduces `PartialWhere` to eliminate the use of duplicate types in `@jovotech/platform-alexa`.
=> :label: Fix typings

clients/client-web-vue2/package.json, clients/client-web-vue3/package.json, clients/client-web/package.json, clients/client-web/src/Client.ts, clients/client-web/src/index.ts, examples/typescript/basic/package.json, package.json, platforms/platform-core/docs/README.md, platforms/platform-core/src/CorePlatform.ts, platforms/platform-core/src/output/CoreOutputTemplateConverterStrategy.ts, platforms/platform-googlebusiness/package.json, platforms/platform-web/package.json, platforms/platform-web/src/index.ts
- Updated dependency versions to hoisted dependency versions
- Re-export model-types of `@jovotech/output` in `@jovotech/client-web` 
- Added additional capability to use a custom key in `OutputTemplate.platforms`
- Improve WebPlatform
=> 👔 Finalize web clients and web platform

integrations/plugin-debugger/src/JovoDebugger.ts
* Fixes `open with "."`
* Fixes closing
=> Fix process.stdin handling 

clients/client-web-vue2/src/index.ts, clients/client-web/JovoLogger-shims.js, clients/client-web/scripts/build.js, clients/client-web/src/Client.ts, clients/client-web/src/core/HttpTransportStrategy.ts, clients/client-web/src/core/NetworkTransportStrategy.ts, clients/client-web/src/index.ts, clients/client-web/tslog-shims.js, clients/client-web/util-shims.js, framework/src/JovoInputBuilder.ts, platforms/platform-googlebusiness/package.json
- Only add truthy values to the input-object
- Remove output-dependency of google-business platform package
- Allow passing a `Client` instance to the Vue2 plugin
- Refactor building of web client
=> 👔 Fix smaller issues

common/src/JovoLogger.ts
=> 🐛 Fix headline style in JovoLogger

integrations/db-filedb/src/FileDb.ts
Add `skipTests: true` to FileDb config.
=> :recycle: Add `skipTests: true` to FileDb default config
